/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 商城平台 API - version 1.0
 *
 * 商城平台接口文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.MallProductsController_findProducts': ['GET', '/mall/products'],
  'general.MallProductsController_findHotProducts': ['GET', '/mall/products/hot'],
  'general.MallProductsController_findProductDetail': ['GET', '/mall/products/{id}'],
  'general.MallHomeController_findCategories': ['GET', '/mall/categories'],
  'general.MallHomeController_findBrands': ['GET', '/mall/brands'],
  'general.MallHomeController_findBanners': ['GET', '/mall/banners'],
  'general.MallAuthController_login': ['POST', '/mall/auth/login'],
  'general.MallAuthController_refresh': ['POST', '/mall/auth/refresh'],
  'general.MallAuthController_wechatLogin': ['POST', '/mall/auth/wechat-login'],
  'general.MallAuthController_getProfile': ['GET', '/mall/auth/me'],
  'general.MallCartController_findCurrentUserCart': ['GET', '/mall/carts/current'],
  'general.MallCartController_addToCart': ['POST', '/mall/carts/add'],
  'general.MallCartController_clearCurrentUserCart': ['DELETE', '/mall/carts/clear'],
  'general.MallCartController_removeCurrentUserCart': ['DELETE', '/mall/carts/{id}'],
  'general.MallAddressesController_findCurrentUserAddresses': ['GET', '/mall/addresses'],
  'general.MallAddressesController_createCurrentUserAddress': ['POST', '/mall/addresses'],
  'general.MallAddressesController_findDefaultAddress': ['GET', '/mall/addresses/default'],
  'general.MallAddressesController_findCurrentUserAddress': ['GET', '/mall/addresses/{id}'],
  'general.MallAddressesController_removeCurrentUserAddress': ['DELETE', '/mall/addresses/{id}'],
  'general.MallOrdersController_findOrders': ['GET', '/mall/orders'],
  'general.MallOrdersController_createOrder': ['POST', '/mall/orders'],
  'general.MallOrdersController_findOrderDetail': ['GET', '/mall/orders/{id}'],
  'general.MallOrdersController_payOrder': ['POST', '/mall/orders/{id}/pay'],
  'general.MallReviewsController_findProductReviews': ['GET', '/mall/products/{id}/reviews'],
  'general.MallReviewsController_getProductReviewStats': ['GET', '/mall/products/{id}/review-stats'],
  'general.MallReviewsController_createReview': ['POST', '/mall/reviews'],
  'general.MallReviewsController_findMyReviews': ['GET', '/mall/reviews/my'],
  'general.MallReviewsController_findPendingReviews': ['GET', '/mall/reviews/pending'],
  'general.MallBalanceController_getSummary': ['GET', '/mall/balance'],
  'general.MallBalanceController_getLogs': ['GET', '/mall/balance/logs'],
  'general.MallBalanceController_recharge': ['POST', '/mall/balance/recharge'],
  'general.MallFavoritesController_findFavorites': ['GET', '/mall/favorites'],
  'general.MallFavoritesController_createFavorite': ['POST', '/mall/favorites'],
  'general.MallFavoritesController_checkFavoriteStatus': ['GET', '/mall/favorites/check'],
  'general.MallFavoritesController_removeFavorite': ['DELETE', '/mall/favorites/{productId}'],
  'general.MallBrowseHistoriesController_findHistories': ['GET', '/mall/histories'],
  'general.MallBrowseHistoriesController_createHistory': ['POST', '/mall/histories'],
  'general.MallBrowseHistoriesController_clearHistories': ['DELETE', '/mall/histories/clear'],
  'general.MallBrowseHistoriesController_removeHistory': ['DELETE', '/mall/histories/{productId}']
};
