/* tslint:disable */
/* eslint-disable */
/**
 * 商城平台 API - version 1.0
 *
 * 商城平台接口文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type Object = object;
export interface WechatLoginDto {
  /**
   * 微信小程序 wx.login 返回的 code
   */
  code: string;
  /**
   * 微信昵称，可选
   */
  nickname?: string;
}
export interface BrandVo {
  /**
   * 品牌ID
   */
  id: number;
  /**
   * 品牌名称
   */
  name: string;
  /**
   * 品牌logo
   */
  logo: object | null;
  /**
   * 品牌描述
   */
  description: object | null;
  /**
   * 排序
   */
  sort: number;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface BannerVo {
  /**
   * 轮播图 ID
   */
  id: number;
  /**
   * 轮播图标题
   */
  title: string;
  /**
   * 轮播图标签
   */
  tag: object | null;
  /**
   * 轮播图子标题
   */
  subtitle: object | null;
  /**
   * 图片地址
   */
  image: string;
  /**
   * 是否启用跳转
   */
  jumpEnabled: boolean;
  /**
   * 跳转路径
   */
  jumpPath: object | null;
  /**
   * 排序号
   */
  sort: number;
  /**
   * 备注
   */
  remark: object | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface CartItemVo {
  /**
   * 购物车ID
   */
  id: number;
  /**
   * 用户ID
   */
  userId: number;
  /**
   * 用户名
   */
  username: string;
  /**
   * SKU ID
   */
  skuId: number;
  /**
   * SKU编码
   */
  skuCode: string;
  /**
   * 规格组合
   */
  specs: object;
  /**
   * 商品ID
   */
  productId: number;
  /**
   * 商品名称
   */
  productName: string;
  /**
   * 商品主图
   */
  mainImage?: object | null;
  /**
   * SKU图片
   */
  skuImage?: object | null;
  /**
   * 单价
   */
  salePrice: number;
  /**
   * 数量
   */
  quantity: number;
  /**
   * 是否选中
   */
  selected: boolean;
  /**
   * 小计金额
   */
  subtotal: number;
  /**
   * 库存数量
   */
  stock: number;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface CartStatsVo {
  /**
   * 购物车商品总数
   */
  totalCount: number;
  /**
   * 选中商品数量
   */
  selectedCount: number;
  /**
   * 选中商品总金额
   */
  selectedAmount: number;
}
export interface CartListVo {
  /**
   * 购物车列表
   */
  list: CartItemVo[];
  /**
   * 统计信息
   */
  stats: CartStatsVo;
}
export interface CategoryVo {
  /**
   * 分类ID
   */
  id: number;
  /**
   * 分类名称
   */
  name: string;
  /**
   * 分类编码
   */
  code: string;
  /**
   * 子标题
   */
  subtitle: object | null;
  /**
   * 备注
   */
  remark: object | null;
  /**
   * 父级ID
   */
  parentId: object | null;
  /**
   * 层级
   */
  level: number;
  /**
   * 排序号
   */
  sort: number;
  /**
   * 分类图标
   */
  icon: object | null;
  /**
   * 分类图标 URL
   */
  iconUrl: object | null;
  /**
   * 分类图片
   */
  image: object | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface UnitVo {
  /**
   * 单位ID
   */
  id: number;
  /**
   * 单位名称
   */
  name: string;
  /**
   * 单位编码
   */
  code: string;
  /**
   * 排序
   */
  sort: number;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface MallProductCardVo {
  /**
   * 商品ID
   */
  id: number;
  /**
   * 商品名称
   */
  name: string;
  /**
   * SPU编码
   */
  spuCode: string;
  /**
   * 分类ID
   */
  categoryId: number;
  /**
   * 品牌ID
   */
  brandId: object | null;
  /**
   * 单位ID
   */
  unitId: number;
  /**
   * 商品描述
   */
  description: object | null;
  /**
   * 商品详情（富文本HTML）
   */
  detail: object | null;
  /**
   * 商品主图
   */
  mainImage: object | null;
  /**
   * 商品图片列表
   */
  images: string[] | null;
  /**
   * 规格模板
   */
  specTemplate: Record<string, any> | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 是否在商城上架
   */
  mallEnabled: boolean;
  /**
   * 总可用库存
   */
  totalAvailable?: number;
  /**
   * 是否有库存
   */
  hasStock?: boolean;
  /**
   * 商城扩展信息
   */
  mallInfo: Record<string, any> | null;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
  /**
   * 分类信息
   */
  category: CategoryVo;
  /**
   * 品牌信息
   */
  brand: BrandVo;
  /**
   * 单位信息
   */
  unit: UnitVo;
  /**
   * SKU列表
   */
  skus?: Array<Record<string, any>>;
  /**
   * 最低价
   */
  minPrice: number;
  /**
   * 最高价
   */
  maxPrice: number;
  /**
   * 价格区间展示文本
   */
  priceRange: string;
}
export interface MallProductListMetaVo {
  /**
   * 当前页码
   */
  page: number;
  /**
   * 每页数量
   */
  pageSize: number;
  /**
   * 总记录数
   */
  total: number;
  /**
   * 总页数
   */
  totalPages: number;
}
export interface MallProductListResponseVo {
  /**
   * 商品列表
   */
  data: MallProductCardVo[];
  /**
   * 分页信息
   */
  meta: MallProductListMetaVo;
}
export interface MallHotProductVo {
  /**
   * 商品ID
   */
  id: number;
  /**
   * 商品名称
   */
  name: string;
  /**
   * 商品主图
   */
  mainImage: object | null;
  /**
   * 最低价
   */
  minPrice: number;
  /**
   * 最高价
   */
  maxPrice: number;
  /**
   * 价格区间展示文本
   */
  priceRange: string;
  /**
   * 热门标签
   */
  hotLabel: string;
  /**
   * 标签类型
   */
  tagType: string;
  /**
   * 来源 manual/score
   */
  source: string;
  /**
   * 热度分数
   */
  hotScore: number;
  /**
   * 销量
   */
  soldCount: number;
  /**
   * 默认SKU ID
   */
  defaultSkuId: object | null;
}
export interface MallHotProductListResponseVo {
  /**
   * 热门商品列表
   */
  list: MallHotProductVo[];
}
export interface MallProductSpecOptionVo {
  /**
   * 规格名称
   */
  name: string;
  /**
   * 规格值列表
   */
  values: string[];
}
export interface MallProductDetailVo {
  /**
   * 商品ID
   */
  id: number;
  /**
   * 商品名称
   */
  name: string;
  /**
   * SPU编码
   */
  spuCode: string;
  /**
   * 分类ID
   */
  categoryId: number;
  /**
   * 品牌ID
   */
  brandId: object | null;
  /**
   * 单位ID
   */
  unitId: number;
  /**
   * 商品描述
   */
  description: object | null;
  /**
   * 商品详情（富文本HTML）
   */
  detail: object | null;
  /**
   * 商品主图
   */
  mainImage: object | null;
  /**
   * 商品图片列表
   */
  images: string[] | null;
  /**
   * 规格模板
   */
  specTemplate: Record<string, any> | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 是否在商城上架
   */
  mallEnabled: boolean;
  /**
   * 总可用库存
   */
  totalAvailable?: number;
  /**
   * 是否有库存
   */
  hasStock?: boolean;
  /**
   * 商城扩展信息
   */
  mallInfo: Record<string, any> | null;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
  /**
   * 分类信息
   */
  category: CategoryVo;
  /**
   * 品牌信息
   */
  brand: BrandVo;
  /**
   * 单位信息
   */
  unit: UnitVo;
  /**
   * SKU列表
   */
  skus?: Array<Record<string, any>>;
  /**
   * 规格选项
   */
  specOptions: MallProductSpecOptionVo[];
}
export interface CategoryTreeVo {
  /**
   * 分类ID
   */
  id: number;
  /**
   * 分类名称
   */
  name: string;
  /**
   * 分类编码
   */
  code: string;
  /**
   * 子标题
   */
  subtitle: object | null;
  /**
   * 备注
   */
  remark: object | null;
  /**
   * 父级ID
   */
  parentId: object | null;
  /**
   * 层级
   */
  level: number;
  /**
   * 排序号
   */
  sort: number;
  /**
   * 分类图标
   */
  icon: object | null;
  /**
   * 分类图标 URL
   */
  iconUrl: object | null;
  /**
   * 分类图片
   */
  image: object | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
  /**
   * 子分类
   */
  children: CategoryTreeVo[] | null;
}
export interface UserVo {
  /**
   * 用户ID
   */
  id: number;
  /**
   * 用户名
   */
  username: string;
  /**
   * 邮箱
   */
  email: object | null;
  /**
   * 姓名
   */
  name: object | null;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface MallWechatLoginVo {
  /**
   * JWT token
   */
  token: string;
  /**
   * 用户信息
   */
  user: UserVo;
}
declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [GET] 获取商城商品列表
       *
       * **path:** /mall/products
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 商品名称关键词搜索
       *   keyword?: string
       *   // 分类ID
       *   categoryId?: number
       *   // 品牌ID
       *   brandId?: number
       *   // 排序: price_asc-价格升序, price_desc-价格降序, new-最新, sales-销量
       *   sort?: string
       *   // 页码
       *   page?: number
       *   // 每页数量
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 商品列表
       *   // [items] start
       *   // [items] end
       *   data: Array<{
       *     // 商品ID
       *     id: number
       *     // 商品名称
       *     name: string
       *     // SPU编码
       *     spuCode: string
       *     // 分类ID
       *     categoryId: number
       *     // 品牌ID
       *     brandId: object | null
       *     // 单位ID
       *     unitId: number
       *     // 商品描述
       *     description: object | null
       *     // 商品详情（富文本HTML）
       *     detail: object | null
       *     // 商品主图
       *     mainImage: object | null
       *     // 商品图片列表
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     images: string[] | null
       *     // 规格模板
       *     specTemplate: Record<string, any> | null
       *     // 是否启用
       *     isEnabled: boolean
       *     // 是否在商城上架
       *     mallEnabled: boolean
       *     // 总可用库存
       *     totalAvailable?: number
       *     // 是否有库存
       *     hasStock?: boolean
       *     // 商城扩展信息
       *     mallInfo: Record<string, any> | null
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *     // 分类信息
       *     category: {
       *       // 分类ID
       *       id: number
       *       // 分类名称
       *       name: string
       *       // 分类编码
       *       code: string
       *       // 子标题
       *       subtitle: object | null
       *       // 备注
       *       remark: object | null
       *       // 父级ID
       *       parentId: object | null
       *       // 层级
       *       level: number
       *       // 排序号
       *       sort: number
       *       // 分类图标
       *       icon: object | null
       *       // 分类图标 URL
       *       iconUrl: object | null
       *       // 分类图片
       *       image: object | null
       *       // 是否启用
       *       isEnabled: boolean
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // 品牌信息
       *     brand: {
       *       // 品牌ID
       *       id: number
       *       // 品牌名称
       *       name: string
       *       // 品牌logo
       *       logo: object | null
       *       // 品牌描述
       *       description: object | null
       *       // 排序
       *       sort: number
       *       // 是否启用
       *       isEnabled: boolean
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // 单位信息
       *     unit: {
       *       // 单位ID
       *       id: number
       *       // 单位名称
       *       name: string
       *       // 单位编码
       *       code: string
       *       // 排序
       *       sort: number
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // SKU列表
       *     // [items] start
       *     // [items] end
       *     skus?: Array<Record<string, any>>
       *     // 最低价
       *     minPrice: number
       *     // 最高价
       *     maxPrice: number
       *     // 价格区间展示文本
       *     priceRange: string
       *   }>
       *   // 分页信息
       *   meta: {
       *     // 当前页码
       *     page: number
       *     // 每页数量
       *     pageSize: number
       *     // 总记录数
       *     total: number
       *     // 总页数
       *     totalPages: number
       *   }
       * }
       * ```
       */
      MallProductsController_findProducts<
        Config extends Alova2MethodConfig<MallProductListResponseVo> & {
          params: {
            /**
             * 商品名称关键词搜索
             */
            keyword?: string;
            /**
             * 分类ID
             */
            categoryId?: number;
            /**
             * 品牌ID
             */
            brandId?: number;
            /**
             * 排序: price_asc-价格升序, price_desc-价格降序, new-最新, sales-销量
             */
            sort?: string;
            /**
             * 页码
             */
            page?: number;
            /**
             * 每页数量
             */
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallProductListResponseVo, 'general.MallProductsController_findProducts', Config>;
      /**
       * ---
       *
       * [GET] 获取热门商品列表
       *
       * **path:** /mall/products/hot
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 返回数量，最大20
       *   limit?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 热门商品列表
       *   // [items] start
       *   // [items] end
       *   list: Array<{
       *     // 商品ID
       *     id: number
       *     // 商品名称
       *     name: string
       *     // 商品主图
       *     mainImage: object | null
       *     // 最低价
       *     minPrice: number
       *     // 最高价
       *     maxPrice: number
       *     // 价格区间展示文本
       *     priceRange: string
       *     // 热门标签
       *     hotLabel: string
       *     // 标签类型
       *     tagType: string
       *     // 来源 manual/score
       *     source: string
       *     // 热度分数
       *     hotScore: number
       *     // 销量
       *     soldCount: number
       *     // 默认SKU ID
       *     defaultSkuId: object | null
       *   }>
       * }
       * ```
       */
      MallProductsController_findHotProducts<
        Config extends Alova2MethodConfig<MallHotProductListResponseVo> & {
          params: {
            /**
             * 返回数量，最大20
             */
            limit?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallHotProductListResponseVo, 'general.MallProductsController_findHotProducts', Config>;
      /**
       * ---
       *
       * [GET] 获取商品详情（商城展示）
       *
       * **path:** /mall/products/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 商品ID
       *   id: number
       *   // 商品名称
       *   name: string
       *   // SPU编码
       *   spuCode: string
       *   // 分类ID
       *   categoryId: number
       *   // 品牌ID
       *   brandId: object | null
       *   // 单位ID
       *   unitId: number
       *   // 商品描述
       *   description: object | null
       *   // 商品详情（富文本HTML）
       *   detail: object | null
       *   // 商品主图
       *   mainImage: object | null
       *   // 商品图片列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   images: string[] | null
       *   // 规格模板
       *   specTemplate: Record<string, any> | null
       *   // 是否启用
       *   isEnabled: boolean
       *   // 是否在商城上架
       *   mallEnabled: boolean
       *   // 总可用库存
       *   totalAvailable?: number
       *   // 是否有库存
       *   hasStock?: boolean
       *   // 商城扩展信息
       *   mallInfo: Record<string, any> | null
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       *   // 分类信息
       *   category: {
       *     // 分类ID
       *     id: number
       *     // 分类名称
       *     name: string
       *     // 分类编码
       *     code: string
       *     // 子标题
       *     subtitle: object | null
       *     // 备注
       *     remark: object | null
       *     // 父级ID
       *     parentId: object | null
       *     // 层级
       *     level: number
       *     // 排序号
       *     sort: number
       *     // 分类图标
       *     icon: object | null
       *     // 分类图标 URL
       *     iconUrl: object | null
       *     // 分类图片
       *     image: object | null
       *     // 是否启用
       *     isEnabled: boolean
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }
       *   // 品牌信息
       *   brand: {
       *     // 品牌ID
       *     id: number
       *     // 品牌名称
       *     name: string
       *     // 品牌logo
       *     logo: object | null
       *     // 品牌描述
       *     description: object | null
       *     // 排序
       *     sort: number
       *     // 是否启用
       *     isEnabled: boolean
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }
       *   // 单位信息
       *   unit: {
       *     // 单位ID
       *     id: number
       *     // 单位名称
       *     name: string
       *     // 单位编码
       *     code: string
       *     // 排序
       *     sort: number
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }
       *   // SKU列表
       *   // [items] start
       *   // [items] end
       *   skus?: Array<Record<string, any>>
       *   // 规格选项
       *   // [items] start
       *   // [items] end
       *   specOptions: Array<{
       *     // 规格名称
       *     name: string
       *     // 规格值列表
       *     // [items] start
       *     // [items] end
       *     values: string[]
       *   }>
       * }
       * ```
       */
      MallProductsController_findProductDetail<
        Config extends Alova2MethodConfig<MallProductDetailVo> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallProductDetailVo, 'general.MallProductsController_findProductDetail', Config>;
      /**
       * ---
       *
       * [GET] 获取启用的分类列表
       *
       * **path:** /mall/categories
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 父级分类ID，传空字符串时筛选一级分类
       *   parentId?: object
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 分类ID
       *   id: number
       *   // 分类名称
       *   name: string
       *   // 分类编码
       *   code: string
       *   // 子标题
       *   subtitle: object | null
       *   // 备注
       *   remark: object | null
       *   // 父级ID
       *   parentId: object | null
       *   // 层级
       *   level: number
       *   // 排序号
       *   sort: number
       *   // 分类图标
       *   icon: object | null
       *   // 分类图标 URL
       *   iconUrl: object | null
       *   // 分类图片
       *   image: object | null
       *   // 是否启用
       *   isEnabled: boolean
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       *   // 子分类
       *   // [params1] start
       *   // [items] start
       *   // [cycle] $.[]
       *   // [items] end
       *   // [params1] end
       *   children: CategoryTreeVo[] | null
       * }>
       * ```
       */
      MallHomeController_findCategories<
        Config extends Alova2MethodConfig<CategoryTreeVo[]> & {
          params: {
            /**
             * 父级分类ID，传空字符串时筛选一级分类
             */
            parentId?: Object;
          };
        }
      >(
        config: Config
      ): Alova2Method<CategoryTreeVo[], 'general.MallHomeController_findCategories', Config>;
      /**
       * ---
       *
       * [GET] 获取启用的品牌列表
       *
       * **path:** /mall/brands
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 品牌ID
       *   id: number
       *   // 品牌名称
       *   name: string
       *   // 品牌logo
       *   logo: object | null
       *   // 品牌描述
       *   description: object | null
       *   // 排序
       *   sort: number
       *   // 是否启用
       *   isEnabled: boolean
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       * }>
       * ```
       */
      MallHomeController_findBrands<Config extends Alova2MethodConfig<BrandVo[]>>(
        config?: Config
      ): Alova2Method<BrandVo[], 'general.MallHomeController_findBrands', Config>;
      /**
       * ---
       *
       * [GET] 获取启用的轮播图列表
       *
       * **path:** /mall/banners
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 轮播图 ID
       *   id: number
       *   // 轮播图标题
       *   title: string
       *   // 轮播图标签
       *   tag: object | null
       *   // 轮播图子标题
       *   subtitle: object | null
       *   // 图片地址
       *   image: string
       *   // 是否启用跳转
       *   jumpEnabled: boolean
       *   // 跳转路径
       *   jumpPath: object | null
       *   // 排序号
       *   sort: number
       *   // 备注
       *   remark: object | null
       *   // 是否启用
       *   isEnabled: boolean
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       * }>
       * ```
       */
      MallHomeController_findBanners<Config extends Alova2MethodConfig<BannerVo[]>>(
        config?: Config
      ): Alova2Method<BannerVo[], 'general.MallHomeController_findBanners', Config>;
      /**
       * ---
       *
       * [POST] 微信授权登录
       *
       * **path:** /mall/auth/wechat-login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 微信小程序 wx.login 返回的 code
       *   code: string
       *   // 微信昵称，可选
       *   nickname?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // JWT token
       *   token: string
       *   // 用户信息
       *   user: {
       *     // 用户ID
       *     id: number
       *     // 用户名
       *     username: string
       *     // 邮箱
       *     email: object | null
       *     // 姓名
       *     name: object | null
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      MallAuthController_wechatLogin<
        Config extends Alova2MethodConfig<MallWechatLoginVo> & {
          data: WechatLoginDto;
        }
      >(
        config: Config
      ): Alova2Method<MallWechatLoginVo, 'general.MallAuthController_wechatLogin', Config>;
      /**
       * ---
       *
       * [GET] 查询当前登录用户购物车
       *
       * **path:** /mall/carts/current
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 购物车列表
       *   // [items] start
       *   // [items] end
       *   list: Array<{
       *     // 购物车ID
       *     id: number
       *     // 用户ID
       *     userId: number
       *     // 用户名
       *     username: string
       *     // SKU ID
       *     skuId: number
       *     // SKU编码
       *     skuCode: string
       *     // 规格组合
       *     specs: object
       *     // 商品ID
       *     productId: number
       *     // 商品名称
       *     productName: string
       *     // 商品主图
       *     mainImage?: object | null
       *     // SKU图片
       *     skuImage?: object | null
       *     // 单价
       *     salePrice: number
       *     // 数量
       *     quantity: number
       *     // 是否选中
       *     selected: boolean
       *     // 小计金额
       *     subtotal: number
       *     // 库存数量
       *     stock: number
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }>
       *   // 统计信息
       *   stats: {
       *     // 购物车商品总数
       *     totalCount: number
       *     // 选中商品数量
       *     selectedCount: number
       *     // 选中商品总金额
       *     selectedAmount: number
       *   }
       * }
       * ```
       */
      MallCartController_findCurrentUserCart<Config extends Alova2MethodConfig<CartListVo>>(
        config?: Config
      ): Alova2Method<CartListVo, 'general.MallCartController_findCurrentUserCart', Config>;
    };
  }

  var Apis: Apis;
}
