/* tslint:disable */
/* eslint-disable */
/**
 * 商城平台 API - version 1.0
 *
 * 商城平台接口文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type Object = object;
export interface MallLoginDto {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 登录密码
   */
  password: string;
}
export interface MallRefreshTokenDto {
  /**
   * 刷新令牌
   */
  refreshToken: string;
}
export interface WechatLoginDto {
  /**
   * 微信小程序 wx.login 返回的 code
   */
  code: string;
  /**
   * 微信手机号授权 code，可选
   */
  phoneCode?: string;
  /**
   * 微信昵称，可选
   */
  nickname?: string;
  /**
   * 微信头像地址，可选
   */
  avatarUrl?: string;
}
export interface AddToCartDto {
  /**
   * SKU ID
   */
  skuId?: number;
  /**
   * 数量
   */
  quantity?: number;
}
export interface CreateCustomerAddressDto {
  /**
   * 收货人
   */
  receiverName: string;
  /**
   * 收货电话
   */
  receiverPhone: string;
  /**
   * 省
   */
  province?: string;
  /**
   * 市
   */
  city?: string;
  /**
   * 区/县
   */
  district?: string;
  /**
   * 详细地址
   */
  address: string;
  /**
   * 邮编
   */
  postalCode?: string;
  /**
   * 地址标签，如家/公司
   */
  tag?: string;
  /**
   * 是否默认地址
   */
  isDefault?: boolean;
  /**
   * 排序值
   */
  sort?: number;
  /**
   * 备注
   */
  remark?: string;
}
export type CreateMallOrderDto = object;
export interface CreateMallReviewDto {
  /**
   * 订单明细ID
   */
  orderItemId: number;
  /**
   * 评分，1-5
   */
  rating: number;
  /**
   * 评价内容
   */
  content?: string;
  /**
   * 评价图片列表
   */
  images?: string[];
  /**
   * 是否匿名
   */
  isAnonymous?: boolean;
}
export interface CreateMallBalanceRechargeDto {
  /**
   * 充值金额
   */
  amount: number;
  /**
   * 充值方式
   */
  method: 'WECHAT';
}
export interface CreateFavoriteDto {
  /**
   * 商品ID
   */
  productId: number;
}
export interface CreateBrowseHistoryDto {
  /**
   * 商品ID
   */
  productId: number;
}
export interface BrandVo {
  /**
   * 品牌ID
   */
  id: number;
  /**
   * 品牌名称
   */
  name: string;
  /**
   * 品牌logo
   */
  logo: object | null;
  /**
   * 品牌描述
   */
  description: object | null;
  /**
   * 排序
   */
  sort: number;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface BannerVo {
  /**
   * 轮播图 ID
   */
  id: number;
  /**
   * 轮播图标题
   */
  title: string;
  /**
   * 轮播图标签
   */
  tag: object | null;
  /**
   * 轮播图子标题
   */
  subtitle: object | null;
  /**
   * 图片地址
   */
  image: string;
  /**
   * 是否启用跳转
   */
  jumpEnabled: boolean;
  /**
   * 跳转路径
   */
  jumpPath: object | null;
  /**
   * 排序号
   */
  sort: number;
  /**
   * 备注
   */
  remark: object | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface MallHotSearchVo {
  /**
   * 热门搜索词 ID
   */
  id: number;
  /**
   * 热门搜索词
   */
  keyword: string;
  /**
   * 排序号
   */
  sort: number;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 搜索次数
   */
  searchCount: number;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface MallCategoryVo {
  /**
   * 分类ID
   */
  id: number;
  /**
   * 分类名称
   */
  name: string;
  /**
   * 分类编码
   */
  code: string;
  /**
   * 子标题
   */
  subtitle: object | null;
  /**
   * 备注
   */
  remark: object | null;
  /**
   * 父级ID
   */
  parentId: object | null;
  /**
   * 层级
   */
  level: number;
  /**
   * 排序号
   */
  sort: number;
  /**
   * 是否作为商城搜索推荐分类
   */
  mallRecommend: boolean;
  /**
   * 商城搜索推荐排序号
   */
  mallRecommendSort: number;
  /**
   * 分类图标
   */
  icon: object | null;
  /**
   * 分类图标 URL
   */
  iconUrl: object | null;
  /**
   * 分类图片
   */
  image: object | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
  /**
   * 分类下商品数量
   */
  productCount: number;
}
export interface MallSearchInitVo {
  /**
   * 热门搜索词列表
   */
  hotKeywords: MallHotSearchVo[];
  /**
   * 推荐分类列表
   */
  recommendCategories: MallCategoryVo[];
}
export interface MallCurrentCustomerVo {
  /**
   * 客户ID
   */
  id: number;
  /**
   * 客户名称
   */
  name: string;
  /**
   * 手机号
   */
  phone: object | null;
  /**
   * 地址
   */
  address: object | null;
  /**
   * 余额账户ID
   */
  balanceAccountId: object | null;
  /**
   * 可用余额
   */
  availableBalance: string | null;
}
export interface MallCurrentUserVo {
  /**
   * 用户ID
   */
  id: number;
  /**
   * 用户名
   */
  username: string;
  /**
   * 邮箱
   */
  email: object | null;
  /**
   * 姓名
   */
  name: object | null;
  /**
   * 头像地址
   */
  avatarUrl: object | null;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
  /**
   * 手机号
   */
  phone: object | null;
  /**
   * 关联客户信息
   */
  customer: MallCurrentCustomerVo;
}
export interface CartItemVo {
  /**
   * 购物车ID
   */
  id: number;
  /**
   * 用户ID
   */
  userId: number;
  /**
   * 用户名
   */
  username: string;
  /**
   * SKU ID
   */
  skuId: number;
  /**
   * SKU编码
   */
  skuCode: string;
  /**
   * 规格组合
   */
  specs: object;
  /**
   * 商品ID
   */
  productId: number;
  /**
   * 商品名称
   */
  productName: string;
  /**
   * 商品主图
   */
  mainImage?: object | null;
  /**
   * SKU图片
   */
  skuImage?: object | null;
  /**
   * 单价
   */
  salePrice: number;
  /**
   * 数量
   */
  quantity: number;
  /**
   * 是否选中
   */
  selected: boolean;
  /**
   * 小计金额
   */
  subtotal: number;
  /**
   * 库存数量
   */
  stock: number;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface CartStatsVo {
  /**
   * 购物车商品总数
   */
  totalCount: number;
  /**
   * 选中商品数量
   */
  selectedCount: number;
  /**
   * 选中商品总金额
   */
  selectedAmount: number;
}
export interface CartListVo {
  /**
   * 购物车列表
   */
  list: CartItemVo[];
  /**
   * 统计信息
   */
  stats: CartStatsVo;
}
export interface CustomerAddressVo {
  /**
   * 地址ID
   */
  id: number;
  /**
   * 客户ID
   */
  customerId: number;
  /**
   * 收货人
   */
  receiverName: string;
  /**
   * 收货电话
   */
  receiverPhone: string;
  /**
   * 省
   */
  province?: object;
  /**
   * 市
   */
  city?: object;
  /**
   * 区/县
   */
  district?: object;
  /**
   * 详细地址
   */
  address: string;
  /**
   * 完整地址
   */
  fullAddress: string;
  /**
   * 邮编
   */
  postalCode?: object;
  /**
   * 标签
   */
  tag?: object;
  /**
   * 是否默认地址
   */
  isDefault: boolean;
  /**
   * 排序值
   */
  sort: number;
  /**
   * 备注
   */
  remark?: object;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface MallOrderItemVo {
  /**
   * 商品ID
   */
  productId: number;
  /**
   * SKU ID
   */
  skuId: number;
  /**
   * 商品名称
   */
  productName: string;
  /**
   * SKU 编码
   */
  skuCode: string;
  /**
   * 规格
   */
  specs: object;
  /**
   * 商品图片
   */
  image: object | null;
  /**
   * 单价
   */
  price: number;
  /**
   * 数量
   */
  quantity: number;
  /**
   * 金额
   */
  amount: number;
}
export interface MallOrderListItemVo {
  /**
   * 订单ID
   */
  id: number;
  /**
   * 订单号
   */
  orderNo: string;
  /**
   * 订单状态
   */
  status: string;
  /**
   * 支付状态
   */
  payStatus: string;
  /**
   * 发货状态
   */
  shipStatus: string;
  /**
   * 下单时间
   */
  orderDate: string;
  /**
   * 支付截止时间
   */
  expireAt: object | null;
  /**
   * 商品总额
   */
  totalAmount: number;
  /**
   * 应付金额
   */
  payable: number;
  /**
   * 已付金额
   */
  paid: number;
  /**
   * 商品件数
   */
  itemCount: number;
  /**
   * 订单商品
   */
  items: MallOrderItemVo[];
}
export interface MallOrderListMetaVo {
  /**
   * 当前页码
   */
  page: number;
  /**
   * 每页数量
   */
  pageSize: number;
  /**
   * 总记录数
   */
  total: number;
  /**
   * 总页数
   */
  totalPages: number;
}
export interface MallOrderListResponseVo {
  /**
   * 订单列表
   */
  data: MallOrderListItemVo[];
  /**
   * 分页信息
   */
  meta: MallOrderListMetaVo;
}
export interface MallBalanceSummaryVo {
  /**
   * 账户ID
   */
  id: number;
  /**
   * 客户ID
   */
  customerId: number;
  /**
   * 可用余额
   */
  availableBalance: string;
  /**
   * 冻结余额
   */
  frozenBalance: string;
  /**
   * 累计充值
   */
  totalRecharged: string;
  /**
   * 累计消费
   */
  totalConsumed: string;
  /**
   * 累计退款
   */
  totalRefunded: string;
  /**
   * 最近更新时间
   */
  updatedAt: string;
}
export interface MallCouponSummaryVo {
  /**
   * 未使用优惠券数量
   */
  unusedCount: number;
  /**
   * 已使用优惠券数量
   */
  usedCount: number;
  /**
   * 已过期优惠券数量
   */
  expiredCount: number;
  /**
   * 可领取优惠券数量
   */
  claimableCount: number;
}
export type PayMallOrderDto = object;
export interface CategoryVo {
  /**
   * 分类ID
   */
  id: number;
  /**
   * 分类名称
   */
  name: string;
  /**
   * 分类编码
   */
  code: string;
  /**
   * 子标题
   */
  subtitle: object | null;
  /**
   * 备注
   */
  remark: object | null;
  /**
   * 父级ID
   */
  parentId: object | null;
  /**
   * 层级
   */
  level: number;
  /**
   * 排序号
   */
  sort: number;
  /**
   * 是否作为商城搜索推荐分类
   */
  mallRecommend: boolean;
  /**
   * 商城搜索推荐排序号
   */
  mallRecommendSort: number;
  /**
   * 分类图标
   */
  icon: object | null;
  /**
   * 分类图标 URL
   */
  iconUrl: object | null;
  /**
   * 分类图片
   */
  image: object | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface UnitVo {
  /**
   * 单位ID
   */
  id: number;
  /**
   * 单位名称
   */
  name: string;
  /**
   * 单位编码
   */
  code: string;
  /**
   * 排序
   */
  sort: number;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
}
export interface MallProductCardVo {
  /**
   * 商品ID
   */
  id: number;
  /**
   * 商品名称
   */
  name: string;
  /**
   * SPU编码
   */
  spuCode: string;
  /**
   * 分类ID
   */
  categoryId: number;
  /**
   * 品牌ID
   */
  brandId: object | null;
  /**
   * 单位ID
   */
  unitId: number;
  /**
   * 商品描述
   */
  description: object | null;
  /**
   * 商品详情（富文本HTML）
   */
  detail: object | null;
  /**
   * 商品主图
   */
  mainImage: object | null;
  /**
   * 商品图片列表
   */
  images: string[] | null;
  /**
   * 规格模板
   */
  specTemplate: Record<string, any> | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 是否在商城上架
   */
  mallEnabled: boolean;
  /**
   * 总可用库存
   */
  totalAvailable?: number;
  /**
   * 是否有库存
   */
  hasStock?: boolean;
  /**
   * 商城扩展信息
   */
  mallInfo: Record<string, any> | null;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
  /**
   * 分类信息
   */
  category: CategoryVo;
  /**
   * 品牌信息
   */
  brand: BrandVo;
  /**
   * 单位信息
   */
  unit: UnitVo;
  /**
   * SKU列表
   */
  skus?: Array<Record<string, any>>;
  /**
   * 当前用户是否已收藏
   */
  isFavorite?: boolean;
  /**
   * 热门标签
   */
  hotLabel?: object | null;
  /**
   * 最低价
   */
  minPrice: number;
  /**
   * 最高价
   */
  maxPrice: number;
  /**
   * 价格区间展示文本
   */
  priceRange: string;
}
export interface MallProductListMetaVo {
  /**
   * 当前页码
   */
  page: number;
  /**
   * 每页数量
   */
  pageSize: number;
  /**
   * 总记录数
   */
  total: number;
  /**
   * 总页数
   */
  totalPages: number;
}
export interface MallProductListResponseVo {
  /**
   * 商品列表
   */
  data: MallProductCardVo[];
  /**
   * 分页信息
   */
  meta: MallProductListMetaVo;
}
export interface MallHotProductVo {
  /**
   * 商品ID
   */
  id: number;
  /**
   * 商品名称
   */
  name: string;
  /**
   * 商品主图
   */
  mainImage: object | null;
  /**
   * 最低价
   */
  minPrice: number;
  /**
   * 最高价
   */
  maxPrice: number;
  /**
   * 价格区间展示文本
   */
  priceRange: string;
  /**
   * 热门标签
   */
  hotLabel: string;
  /**
   * 标签类型
   */
  tagType: string;
  /**
   * 来源 manual/score
   */
  source: string;
  /**
   * 热度分数
   */
  hotScore: number;
  /**
   * 销量
   */
  soldCount: number;
  /**
   * 默认SKU ID
   */
  defaultSkuId: object | null;
}
export interface MallHotProductListResponseVo {
  /**
   * 热门商品列表
   */
  list: MallHotProductVo[];
}
export interface MallProductSpecOptionVo {
  /**
   * 规格名称
   */
  name: string;
  /**
   * 规格值列表
   */
  values: string[];
}
export interface MallProductDetailVo {
  /**
   * 商品ID
   */
  id: number;
  /**
   * 商品名称
   */
  name: string;
  /**
   * SPU编码
   */
  spuCode: string;
  /**
   * 分类ID
   */
  categoryId: number;
  /**
   * 品牌ID
   */
  brandId: object | null;
  /**
   * 单位ID
   */
  unitId: number;
  /**
   * 商品描述
   */
  description: object | null;
  /**
   * 商品详情（富文本HTML）
   */
  detail: object | null;
  /**
   * 商品主图
   */
  mainImage: object | null;
  /**
   * 商品图片列表
   */
  images: string[] | null;
  /**
   * 规格模板
   */
  specTemplate: Record<string, any> | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 是否在商城上架
   */
  mallEnabled: boolean;
  /**
   * 总可用库存
   */
  totalAvailable?: number;
  /**
   * 是否有库存
   */
  hasStock?: boolean;
  /**
   * 商城扩展信息
   */
  mallInfo: Record<string, any> | null;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
  /**
   * 分类信息
   */
  category: CategoryVo;
  /**
   * 品牌信息
   */
  brand: BrandVo;
  /**
   * 单位信息
   */
  unit: UnitVo;
  /**
   * SKU列表
   */
  skus?: Array<Record<string, any>>;
  /**
   * 当前用户是否已收藏
   */
  isFavorite?: boolean;
  /**
   * 规格选项
   */
  specOptions: MallProductSpecOptionVo[];
}
export interface MallTokenPairVo {
  /**
   * JWT token
   */
  token: string;
  /**
   * 刷新 token
   */
  refreshToken: string;
}
export interface MallWechatLoginVo {
  /**
   * JWT token
   */
  token: string;
  /**
   * 刷新 token
   */
  refreshToken: string;
  /**
   * 用户信息
   */
  user: MallCurrentUserVo;
  /**
   * 是否已完成资料设置
   */
  profileCompleted: boolean;
}
export interface MallCreateOrderVo {
  /**
   * 订单ID
   */
  id: number;
  /**
   * 订单号
   */
  orderNo: string;
  /**
   * 订单来源
   */
  source: 'cart' | 'product-detail';
  /**
   * 商品总金额
   */
  totalAmount: number;
  /**
   * 应付金额
   */
  payable: number;
  /**
   * 优惠金额
   */
  discount: number;
  /**
   * 优惠券领取记录 ID
   */
  couponReceiveId: object | null;
  /**
   * 优惠券名称
   */
  couponName: object | null;
  /**
   * 商品件数
   */
  itemCount: number;
  /**
   * 订单状态
   */
  status: string;
  /**
   * 支付状态
   */
  payStatus: string;
  /**
   * 支付截止时间
   */
  expireAt?: object | null;
}
export interface MallOrderDetailVo {
  /**
   * 订单ID
   */
  id: number;
  /**
   * 订单号
   */
  orderNo: string;
  /**
   * 订单状态
   */
  status: string;
  /**
   * 支付状态
   */
  payStatus: string;
  /**
   * 发货状态
   */
  shipStatus: string;
  /**
   * 下单时间
   */
  orderDate: string;
  /**
   * 支付截止时间
   */
  expireAt: object | null;
  /**
   * 商品总额
   */
  totalAmount: number;
  /**
   * 应付金额
   */
  payable: number;
  /**
   * 已付金额
   */
  paid: number;
  /**
   * 商品件数
   */
  itemCount: number;
  /**
   * 订单商品
   */
  items: MallOrderItemVo[];
  /**
   * 收货人
   */
  receiverName: object | null;
  /**
   * 收货电话
   */
  receiverPhone: object | null;
  /**
   * 收货地址
   */
  receiverAddress: object | null;
  /**
   * 优惠金额
   */
  discount: number;
  /**
   * 运费
   */
  freight: number;
  /**
   * 支付时间
   */
  payDate: object | null;
  /**
   * 取消时间
   */
  cancelDate: object | null;
  /**
   * 发货时间
   */
  shipDate: object | null;
  /**
   * 收货时间
   */
  receiveDate: object | null;
  /**
   * 支付方式
   */
  paymentMethod: object | null;
  /**
   * 优惠券领取记录 ID
   */
  couponReceiveId: object | null;
  /**
   * 优惠券名称
   */
  couponName: object | null;
}
export interface MallPayOrderVo {
  /**
   * 支付单ID
   */
  paymentId: object | null;
  /**
   * 订单ID
   */
  id: number;
  /**
   * 订单号
   */
  orderNo: string;
  /**
   * 支付状态
   */
  payStatus: string;
  /**
   * 订单状态
   */
  status: string;
  /**
   * 已付金额
   */
  paid: number;
  /**
   * 支付单状态
   */
  paymentStatus: string;
  /**
   * 支付方式
   */
  method: object | null;
  /**
   * 商户支付单号
   */
  outTradeNo: object | null;
  /**
   * 支付完成时间
   */
  payDate: object | null;
  /**
   * 微信小程序支付参数
   */
  paymentConfig?: object | null;
}
export interface MallBalanceLogVo {
  /**
   * 流水ID
   */
  id: number;
  /**
   * 流水类型
   */
  type: 'RECHARGE' | 'CONSUME' | 'REFUND' | 'ADJUST_INCREASE' | 'ADJUST_DECREASE';
  /**
   * 流水类型文案
   */
  typeText: string;
  /**
   * 变动金额
   */
  changeAmount: string;
  /**
   * 变动前余额
   */
  balanceBefore: string;
  /**
   * 变动后余额
   */
  balanceAfter: string;
  /**
   * 业务单号
   */
  bizNo?: object | null;
  /**
   * 备注
   */
  remark?: object | null;
  /**
   * 创建时间
   */
  createdAt: string;
}
export interface MallBalanceLogListVo {
  data: MallBalanceLogVo[];
  /**
   * 分页信息
   */
  meta: object;
}
export interface MallBalanceRechargeVo {
  /**
   * 充值单ID
   */
  id: number;
  /**
   * 账户ID
   */
  accountId: number;
  /**
   * 充值金额
   */
  amount: string;
  /**
   * 充值方式
   */
  method: 'CASH' | 'BANK' | 'ALIPAY' | 'WECHAT' | 'CREDIT' | 'BALANCE';
  /**
   * 当前可用余额
   */
  availableBalance: string;
  /**
   * 充值单号
   */
  rechargeNo: string;
  /**
   * 充值状态
   */
  status: string;
  /**
   * 商户支付单号
   */
  outTradeNo: object | null;
  /**
   * 微信小程序支付参数
   */
  paymentConfig?: object | null;
  /**
   * 充值时间
   */
  createdAt: string;
  /**
   * 支付完成时间
   */
  paidAt: object | null;
}
export interface FavoriteItemVo {
  /**
   * 商品ID
   */
  id: number;
  /**
   * 商品名称
   */
  name: string;
  /**
   * SPU编码
   */
  spuCode: string;
  /**
   * 分类ID
   */
  categoryId: number;
  /**
   * 品牌ID
   */
  brandId: object | null;
  /**
   * 单位ID
   */
  unitId: number;
  /**
   * 商品描述
   */
  description: object | null;
  /**
   * 商品详情（富文本HTML）
   */
  detail: object | null;
  /**
   * 商品主图
   */
  mainImage: object | null;
  /**
   * 商品图片列表
   */
  images: string[] | null;
  /**
   * 规格模板
   */
  specTemplate: Record<string, any> | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 是否在商城上架
   */
  mallEnabled: boolean;
  /**
   * 总可用库存
   */
  totalAvailable?: number;
  /**
   * 是否有库存
   */
  hasStock?: boolean;
  /**
   * 商城扩展信息
   */
  mallInfo: Record<string, any> | null;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
  /**
   * 分类信息
   */
  category: CategoryVo;
  /**
   * 品牌信息
   */
  brand: BrandVo;
  /**
   * 单位信息
   */
  unit: UnitVo;
  /**
   * SKU列表
   */
  skus?: Array<Record<string, any>>;
  /**
   * 当前用户是否已收藏
   */
  isFavorite?: boolean;
  /**
   * 热门标签
   */
  hotLabel?: object | null;
  /**
   * 最低价
   */
  minPrice: number;
  /**
   * 最高价
   */
  maxPrice: number;
  /**
   * 价格区间展示文本
   */
  priceRange: string;
  /**
   * 收藏ID
   */
  favoriteId: number;
  /**
   * 收藏时间
   */
  favoriteAt: string;
}
export interface FavoriteListVo {
  data: FavoriteItemVo[];
  meta: MallProductListMetaVo;
}
export interface FavoriteStatusVo {
  /**
   * 商品ID
   */
  productId: number;
  /**
   * 是否已收藏
   */
  isFavorite: boolean;
}
export interface BrowseHistoryItemVo {
  /**
   * 商品ID
   */
  id: number;
  /**
   * 商品名称
   */
  name: string;
  /**
   * SPU编码
   */
  spuCode: string;
  /**
   * 分类ID
   */
  categoryId: number;
  /**
   * 品牌ID
   */
  brandId: object | null;
  /**
   * 单位ID
   */
  unitId: number;
  /**
   * 商品描述
   */
  description: object | null;
  /**
   * 商品详情（富文本HTML）
   */
  detail: object | null;
  /**
   * 商品主图
   */
  mainImage: object | null;
  /**
   * 商品图片列表
   */
  images: string[] | null;
  /**
   * 规格模板
   */
  specTemplate: Record<string, any> | null;
  /**
   * 是否启用
   */
  isEnabled: boolean;
  /**
   * 是否在商城上架
   */
  mallEnabled: boolean;
  /**
   * 总可用库存
   */
  totalAvailable?: number;
  /**
   * 是否有库存
   */
  hasStock?: boolean;
  /**
   * 商城扩展信息
   */
  mallInfo: Record<string, any> | null;
  /**
   * 创建时间
   */
  createdAt: string;
  /**
   * 更新时间
   */
  updatedAt: string;
  /**
   * 分类信息
   */
  category: CategoryVo;
  /**
   * 品牌信息
   */
  brand: BrandVo;
  /**
   * 单位信息
   */
  unit: UnitVo;
  /**
   * SKU列表
   */
  skus?: Array<Record<string, any>>;
  /**
   * 当前用户是否已收藏
   */
  isFavorite?: boolean;
  /**
   * 热门标签
   */
  hotLabel?: object | null;
  /**
   * 最低价
   */
  minPrice: number;
  /**
   * 最高价
   */
  maxPrice: number;
  /**
   * 价格区间展示文本
   */
  priceRange: string;
  /**
   * 浏览记录ID
   */
  historyId: number;
  /**
   * 浏览次数
   */
  viewCount: number;
  /**
   * 首次浏览时间
   */
  firstViewedAt: string;
  /**
   * 最近浏览时间
   */
  lastViewedAt: string;
}
export interface BrowseHistoryListVo {
  data: BrowseHistoryItemVo[];
  meta: MallProductListMetaVo;
}
export interface MallCouponWalletItemVo {
  /**
   * 领取记录 ID
   */
  id: number;
  /**
   * 优惠券 ID
   */
  couponId: number;
  /**
   * 优惠券名称
   */
  name: string;
  /**
   * 优惠券编码
   */
  code: string;
  /**
   * 优惠券金额
   */
  discountAmount: number;
  /**
   * 使用门槛金额
   */
  thresholdAmount: number;
  /**
   * 优惠文案
   */
  discountLabel: string;
  /**
   * 使用门槛文案
   */
  thresholdLabel: string;
  /**
   * 状态
   */
  status: 'UNUSED' | 'USED' | 'EXPIRED' | 'INVALID';
  /**
   * 状态文案
   */
  statusText: string;
  /**
   * 来源文案
   */
  sourceText: string;
  /**
   * 有效期开始时间
   */
  validFrom: string;
  /**
   * 有效期结束时间
   */
  validTo: string;
  /**
   * 有效期文案
   */
  validPeriodText: string;
  /**
   * 使用说明
   */
  description: object | null;
  /**
   * 是否临近到期
   */
  isExpiringSoon: boolean;
}
export interface MallCouponWalletListVo {
  data: MallCouponWalletItemVo[];
  meta: MallProductListMetaVo;
}
export interface MallCouponCenterItemVo {
  /**
   * 优惠券 ID
   */
  id: number;
  /**
   * 优惠券名称
   */
  name: string;
  /**
   * 优惠券编码
   */
  code: string;
  /**
   * 优惠券金额
   */
  discountAmount: number;
  /**
   * 使用门槛金额
   */
  thresholdAmount: number;
  /**
   * 优惠文案
   */
  discountLabel: string;
  /**
   * 使用门槛文案
   */
  thresholdLabel: string;
  /**
   * 剩余数量
   */
  remainingCount: object | null;
  /**
   * 个人已领取次数
   */
  claimedCount: number;
  /**
   * 是否可领取
   */
  canClaim: boolean;
  /**
   * 按钮文案
   */
  actionText: string;
  /**
   * 标签文案
   */
  tagText: object | null;
  /**
   * 有效期开始时间
   */
  startTime: string;
  /**
   * 有效期结束时间
   */
  endTime: string;
  /**
   * 有效期文案
   */
  validPeriodText: string;
  /**
   * 使用说明
   */
  description: object | null;
}
export interface MallCouponCenterListVo {
  data: MallCouponCenterItemVo[];
  meta: MallProductListMetaVo;
}
export interface MallCouponClaimResultVo {
  /**
   * 是否成功
   */
  success: boolean;
  /**
   * 提示信息
   */
  message: string;
}
declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [GET] 获取商城商品列表
       *
       * **path:** /mall/products
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 商品名称关键词搜索
       *   keyword?: string
       *   // 分类ID
       *   categoryId?: number
       *   // 品牌ID
       *   brandId?: number
       *   // 排序: recommended-推荐, price_asc-价格升序, price_desc-价格降序, new-最新, sales-销量
       *   sort?: string
       *   // 页码
       *   page?: number
       *   // 每页数量
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 商品列表
       *   // [items] start
       *   // [items] end
       *   data: Array<{
       *     // 商品ID
       *     id: number
       *     // 商品名称
       *     name: string
       *     // SPU编码
       *     spuCode: string
       *     // 分类ID
       *     categoryId: number
       *     // 品牌ID
       *     brandId: object | null
       *     // 单位ID
       *     unitId: number
       *     // 商品描述
       *     description: object | null
       *     // 商品详情（富文本HTML）
       *     detail: object | null
       *     // 商品主图
       *     mainImage: object | null
       *     // 商品图片列表
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     images: string[] | null
       *     // 规格模板
       *     specTemplate: Record<string, any> | null
       *     // 是否启用
       *     isEnabled: boolean
       *     // 是否在商城上架
       *     mallEnabled: boolean
       *     // 总可用库存
       *     totalAvailable?: number
       *     // 是否有库存
       *     hasStock?: boolean
       *     // 商城扩展信息
       *     mallInfo: Record<string, any> | null
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *     // 分类信息
       *     category: {
       *       // 分类ID
       *       id: number
       *       // 分类名称
       *       name: string
       *       // 分类编码
       *       code: string
       *       // 子标题
       *       subtitle: object | null
       *       // 备注
       *       remark: object | null
       *       // 父级ID
       *       parentId: object | null
       *       // 层级
       *       level: number
       *       // 排序号
       *       sort: number
       *       // 是否作为商城搜索推荐分类
       *       mallRecommend: boolean
       *       // 商城搜索推荐排序号
       *       mallRecommendSort: number
       *       // 分类图标
       *       icon: object | null
       *       // 分类图标 URL
       *       iconUrl: object | null
       *       // 分类图片
       *       image: object | null
       *       // 是否启用
       *       isEnabled: boolean
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // 品牌信息
       *     brand: {
       *       // 品牌ID
       *       id: number
       *       // 品牌名称
       *       name: string
       *       // 品牌logo
       *       logo: object | null
       *       // 品牌描述
       *       description: object | null
       *       // 排序
       *       sort: number
       *       // 是否启用
       *       isEnabled: boolean
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // 单位信息
       *     unit: {
       *       // 单位ID
       *       id: number
       *       // 单位名称
       *       name: string
       *       // 单位编码
       *       code: string
       *       // 排序
       *       sort: number
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // SKU列表
       *     // [items] start
       *     // [items] end
       *     skus?: Array<Record<string, any>>
       *     // 当前用户是否已收藏
       *     isFavorite?: boolean
       *     // 热门标签
       *     hotLabel?: object | null
       *     // 最低价
       *     minPrice: number
       *     // 最高价
       *     maxPrice: number
       *     // 价格区间展示文本
       *     priceRange: string
       *   }>
       *   // 分页信息
       *   meta: {
       *     // 当前页码
       *     page: number
       *     // 每页数量
       *     pageSize: number
       *     // 总记录数
       *     total: number
       *     // 总页数
       *     totalPages: number
       *   }
       * }
       * ```
       */
      MallProductsController_findProducts<
        Config extends Alova2MethodConfig<MallProductListResponseVo> & {
          params: {
            /**
             * 商品名称关键词搜索
             */
            keyword?: string;
            /**
             * 分类ID
             */
            categoryId?: number;
            /**
             * 品牌ID
             */
            brandId?: number;
            /**
             * 排序: recommended-推荐, price_asc-价格升序, price_desc-价格降序, new-最新, sales-销量
             */
            sort?: string;
            /**
             * 页码
             */
            page?: number;
            /**
             * 每页数量
             */
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallProductListResponseVo, 'general.MallProductsController_findProducts', Config>;
      /**
       * ---
       *
       * [GET] 获取热门商品列表
       *
       * **path:** /mall/products/hot
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 返回数量，最大20
       *   limit?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 热门商品列表
       *   // [items] start
       *   // [items] end
       *   list: Array<{
       *     // 商品ID
       *     id: number
       *     // 商品名称
       *     name: string
       *     // 商品主图
       *     mainImage: object | null
       *     // 最低价
       *     minPrice: number
       *     // 最高价
       *     maxPrice: number
       *     // 价格区间展示文本
       *     priceRange: string
       *     // 热门标签
       *     hotLabel: string
       *     // 标签类型
       *     tagType: string
       *     // 来源 manual/score
       *     source: string
       *     // 热度分数
       *     hotScore: number
       *     // 销量
       *     soldCount: number
       *     // 默认SKU ID
       *     defaultSkuId: object | null
       *   }>
       * }
       * ```
       */
      MallProductsController_findHotProducts<
        Config extends Alova2MethodConfig<MallHotProductListResponseVo> & {
          params: {
            /**
             * 返回数量，最大20
             */
            limit?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallHotProductListResponseVo, 'general.MallProductsController_findHotProducts', Config>;
      /**
       * ---
       *
       * [GET] 获取商品详情（商城展示）
       *
       * **path:** /mall/products/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 商品ID
       *   id: number
       *   // 商品名称
       *   name: string
       *   // SPU编码
       *   spuCode: string
       *   // 分类ID
       *   categoryId: number
       *   // 品牌ID
       *   brandId: object | null
       *   // 单位ID
       *   unitId: number
       *   // 商品描述
       *   description: object | null
       *   // 商品详情（富文本HTML）
       *   detail: object | null
       *   // 商品主图
       *   mainImage: object | null
       *   // 商品图片列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   images: string[] | null
       *   // 规格模板
       *   specTemplate: Record<string, any> | null
       *   // 是否启用
       *   isEnabled: boolean
       *   // 是否在商城上架
       *   mallEnabled: boolean
       *   // 总可用库存
       *   totalAvailable?: number
       *   // 是否有库存
       *   hasStock?: boolean
       *   // 商城扩展信息
       *   mallInfo: Record<string, any> | null
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       *   // 分类信息
       *   category: {
       *     // 分类ID
       *     id: number
       *     // 分类名称
       *     name: string
       *     // 分类编码
       *     code: string
       *     // 子标题
       *     subtitle: object | null
       *     // 备注
       *     remark: object | null
       *     // 父级ID
       *     parentId: object | null
       *     // 层级
       *     level: number
       *     // 排序号
       *     sort: number
       *     // 是否作为商城搜索推荐分类
       *     mallRecommend: boolean
       *     // 商城搜索推荐排序号
       *     mallRecommendSort: number
       *     // 分类图标
       *     icon: object | null
       *     // 分类图标 URL
       *     iconUrl: object | null
       *     // 分类图片
       *     image: object | null
       *     // 是否启用
       *     isEnabled: boolean
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }
       *   // 品牌信息
       *   brand: {
       *     // 品牌ID
       *     id: number
       *     // 品牌名称
       *     name: string
       *     // 品牌logo
       *     logo: object | null
       *     // 品牌描述
       *     description: object | null
       *     // 排序
       *     sort: number
       *     // 是否启用
       *     isEnabled: boolean
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }
       *   // 单位信息
       *   unit: {
       *     // 单位ID
       *     id: number
       *     // 单位名称
       *     name: string
       *     // 单位编码
       *     code: string
       *     // 排序
       *     sort: number
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }
       *   // SKU列表
       *   // [items] start
       *   // [items] end
       *   skus?: Array<Record<string, any>>
       *   // 当前用户是否已收藏
       *   isFavorite?: boolean
       *   // 规格选项
       *   // [items] start
       *   // [items] end
       *   specOptions: Array<{
       *     // 规格名称
       *     name: string
       *     // 规格值列表
       *     // [items] start
       *     // [items] end
       *     values: string[]
       *   }>
       * }
       * ```
       */
      MallProductsController_findProductDetail<
        Config extends Alova2MethodConfig<MallProductDetailVo> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallProductDetailVo, 'general.MallProductsController_findProductDetail', Config>;
      /**
       * ---
       *
       * [GET] 获取启用的分类列表
       *
       * **path:** /mall/categories
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 父级分类ID，传空字符串时筛选一级分类
       *   parentId?: object
       *   // 是否仅返回商城搜索推荐分类
       *   recommendOnly?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 分类ID
       *   id: number
       *   // 分类名称
       *   name: string
       *   // 分类编码
       *   code: string
       *   // 子标题
       *   subtitle: object | null
       *   // 备注
       *   remark: object | null
       *   // 父级ID
       *   parentId: object | null
       *   // 层级
       *   level: number
       *   // 排序号
       *   sort: number
       *   // 是否作为商城搜索推荐分类
       *   mallRecommend: boolean
       *   // 商城搜索推荐排序号
       *   mallRecommendSort: number
       *   // 分类图标
       *   icon: object | null
       *   // 分类图标 URL
       *   iconUrl: object | null
       *   // 分类图片
       *   image: object | null
       *   // 是否启用
       *   isEnabled: boolean
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       *   // 分类下商品数量
       *   productCount: number
       * }>
       * ```
       */
      MallHomeController_findCategories<
        Config extends Alova2MethodConfig<MallCategoryVo[]> & {
          params: {
            /**
             * 父级分类ID，传空字符串时筛选一级分类
             */
            parentId?: Object;
            /**
             * 是否仅返回商城搜索推荐分类
             */
            recommendOnly?: boolean;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallCategoryVo[], 'general.MallHomeController_findCategories', Config>;
      /**
       * ---
       *
       * [GET] 获取启用的品牌列表
       *
       * **path:** /mall/brands
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 品牌ID
       *   id: number
       *   // 品牌名称
       *   name: string
       *   // 品牌logo
       *   logo: object | null
       *   // 品牌描述
       *   description: object | null
       *   // 排序
       *   sort: number
       *   // 是否启用
       *   isEnabled: boolean
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       * }>
       * ```
       */
      MallHomeController_findBrands<Config extends Alova2MethodConfig<BrandVo[]>>(
        config?: Config
      ): Alova2Method<BrandVo[], 'general.MallHomeController_findBrands', Config>;
      /**
       * ---
       *
       * [GET] 获取启用的轮播图列表
       *
       * **path:** /mall/banners
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 轮播图 ID
       *   id: number
       *   // 轮播图标题
       *   title: string
       *   // 轮播图标签
       *   tag: object | null
       *   // 轮播图子标题
       *   subtitle: object | null
       *   // 图片地址
       *   image: string
       *   // 是否启用跳转
       *   jumpEnabled: boolean
       *   // 跳转路径
       *   jumpPath: object | null
       *   // 排序号
       *   sort: number
       *   // 备注
       *   remark: object | null
       *   // 是否启用
       *   isEnabled: boolean
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       * }>
       * ```
       */
      MallHomeController_findBanners<Config extends Alova2MethodConfig<BannerVo[]>>(
        config?: Config
      ): Alova2Method<BannerVo[], 'general.MallHomeController_findBanners', Config>;
      /**
       * ---
       *
       * [GET] 获取搜索页初始化数据
       *
       * **path:** /mall/search/init
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 热门搜索词列表
       *   // [items] start
       *   // [items] end
       *   hotKeywords: Array<{
       *     // 热门搜索词 ID
       *     id: number
       *     // 热门搜索词
       *     keyword: string
       *     // 排序号
       *     sort: number
       *     // 是否启用
       *     isEnabled: boolean
       *     // 搜索次数
       *     searchCount: number
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }>
       *   // 推荐分类列表
       *   // [items] start
       *   // [items] end
       *   recommendCategories: Array<{
       *     // 分类ID
       *     id: number
       *     // 分类名称
       *     name: string
       *     // 分类编码
       *     code: string
       *     // 子标题
       *     subtitle: object | null
       *     // 备注
       *     remark: object | null
       *     // 父级ID
       *     parentId: object | null
       *     // 层级
       *     level: number
       *     // 排序号
       *     sort: number
       *     // 是否作为商城搜索推荐分类
       *     mallRecommend: boolean
       *     // 商城搜索推荐排序号
       *     mallRecommendSort: number
       *     // 分类图标
       *     icon: object | null
       *     // 分类图标 URL
       *     iconUrl: object | null
       *     // 分类图片
       *     image: object | null
       *     // 是否启用
       *     isEnabled: boolean
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *     // 分类下商品数量
       *     productCount: number
       *   }>
       * }
       * ```
       */
      MallHomeController_findSearchInit<Config extends Alova2MethodConfig<MallSearchInitVo>>(
        config?: Config
      ): Alova2Method<MallSearchInitVo, 'general.MallHomeController_findSearchInit', Config>;
      /**
       * ---
       *
       * [POST] 手机号密码登录
       *
       * **path:** /mall/auth/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       *   // 登录密码
       *   password: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // JWT token
       *   token: string
       *   // 刷新 token
       *   refreshToken: string
       * }
       * ```
       */
      MallAuthController_login<
        Config extends Alova2MethodConfig<MallTokenPairVo> & {
          data: MallLoginDto;
        }
      >(
        config: Config
      ): Alova2Method<MallTokenPairVo, 'general.MallAuthController_login', Config>;
      /**
       * ---
       *
       * [POST] 刷新登录令牌
       *
       * **path:** /mall/auth/refresh
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 刷新令牌
       *   refreshToken: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // JWT token
       *   token: string
       *   // 刷新 token
       *   refreshToken: string
       * }
       * ```
       */
      MallAuthController_refresh<
        Config extends Alova2MethodConfig<MallTokenPairVo> & {
          data: MallRefreshTokenDto;
        }
      >(
        config: Config
      ): Alova2Method<MallTokenPairVo, 'general.MallAuthController_refresh', Config>;
      /**
       * ---
       *
       * [POST] 微信授权登录
       *
       * **path:** /mall/auth/wechat-login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 微信小程序 wx.login 返回的 code
       *   code: string
       *   // 微信手机号授权 code，可选
       *   phoneCode?: string
       *   // 微信昵称，可选
       *   nickname?: string
       *   // 微信头像地址，可选
       *   avatarUrl?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // JWT token
       *   token: string
       *   // 刷新 token
       *   refreshToken: string
       *   // 用户信息
       *   user: {
       *     // 用户ID
       *     id: number
       *     // 用户名
       *     username: string
       *     // 邮箱
       *     email: object | null
       *     // 姓名
       *     name: object | null
       *     // 头像地址
       *     avatarUrl: object | null
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *     // 手机号
       *     phone: object | null
       *     // 关联客户信息
       *     customer: {
       *       // 客户ID
       *       id: number
       *       // 客户名称
       *       name: string
       *       // 手机号
       *       phone: object | null
       *       // 地址
       *       address: object | null
       *       // 余额账户ID
       *       balanceAccountId: object | null
       *       // 可用余额
       *       availableBalance: string | null
       *     }
       *   }
       *   // 是否已完成资料设置
       *   profileCompleted: boolean
       * }
       * ```
       */
      MallAuthController_wechatLogin<
        Config extends Alova2MethodConfig<MallWechatLoginVo> & {
          data: WechatLoginDto;
        }
      >(
        config: Config
      ): Alova2Method<MallWechatLoginVo, 'general.MallAuthController_wechatLogin', Config>;
      /**
       * ---
       *
       * [GET] 获取当前商城登录用户信息
       *
       * **path:** /mall/auth/me
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 用户ID
       *   id: number
       *   // 用户名
       *   username: string
       *   // 邮箱
       *   email: object | null
       *   // 姓名
       *   name: object | null
       *   // 头像地址
       *   avatarUrl: object | null
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       *   // 手机号
       *   phone: object | null
       *   // 关联客户信息
       *   customer: {
       *     // 客户ID
       *     id: number
       *     // 客户名称
       *     name: string
       *     // 手机号
       *     phone: object | null
       *     // 地址
       *     address: object | null
       *     // 余额账户ID
       *     balanceAccountId: object | null
       *     // 可用余额
       *     availableBalance: string | null
       *   }
       * }
       * ```
       */
      MallAuthController_getProfile<Config extends Alova2MethodConfig<MallCurrentUserVo>>(
        config?: Config
      ): Alova2Method<MallCurrentUserVo, 'general.MallAuthController_getProfile', Config>;
      /**
       * ---
       *
       * [GET] 查询当前登录用户购物车
       *
       * **path:** /mall/carts/current
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 购物车列表
       *   // [items] start
       *   // [items] end
       *   list: Array<{
       *     // 购物车ID
       *     id: number
       *     // 用户ID
       *     userId: number
       *     // 用户名
       *     username: string
       *     // SKU ID
       *     skuId: number
       *     // SKU编码
       *     skuCode: string
       *     // 规格组合
       *     specs: object
       *     // 商品ID
       *     productId: number
       *     // 商品名称
       *     productName: string
       *     // 商品主图
       *     mainImage?: object | null
       *     // SKU图片
       *     skuImage?: object | null
       *     // 单价
       *     salePrice: number
       *     // 数量
       *     quantity: number
       *     // 是否选中
       *     selected: boolean
       *     // 小计金额
       *     subtotal: number
       *     // 库存数量
       *     stock: number
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *   }>
       *   // 统计信息
       *   stats: {
       *     // 购物车商品总数
       *     totalCount: number
       *     // 选中商品数量
       *     selectedCount: number
       *     // 选中商品总金额
       *     selectedAmount: number
       *   }
       * }
       * ```
       */
      MallCartController_findCurrentUserCart<Config extends Alova2MethodConfig<CartListVo>>(
        config?: Config
      ): Alova2Method<CartListVo, 'general.MallCartController_findCurrentUserCart', Config>;
      /**
       * ---
       *
       * [POST] 添加商品到购物车
       *
       * **path:** /mall/carts/add
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // SKU ID
       *   skuId?: number
       *   // 数量
       *   quantity?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallCartController_addToCart<
        Config extends Alova2MethodConfig<null> & {
          data: AddToCartDto;
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallCartController_addToCart', Config>;
      /**
       * ---
       *
       * [DELETE] 清空当前登录用户购物车
       *
       * **path:** /mall/carts/clear
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallCartController_clearCurrentUserCart<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'general.MallCartController_clearCurrentUserCart', Config>;
      /**
       * ---
       *
       * [DELETE] 删除当前登录用户购物车项
       *
       * **path:** /mall/carts/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallCartController_removeCurrentUserCart<
        Config extends Alova2MethodConfig<null> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallCartController_removeCurrentUserCart', Config>;
      /**
       * ---
       *
       * [GET] 获取当前登录用户收货地址列表
       *
       * **path:** /mall/addresses
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 地址ID
       *   id: number
       *   // 客户ID
       *   customerId: number
       *   // 收货人
       *   receiverName: string
       *   // 收货电话
       *   receiverPhone: string
       *   // 省
       *   province?: object
       *   // 市
       *   city?: object
       *   // 区/县
       *   district?: object
       *   // 详细地址
       *   address: string
       *   // 完整地址
       *   fullAddress: string
       *   // 邮编
       *   postalCode?: object
       *   // 标签
       *   tag?: object
       *   // 是否默认地址
       *   isDefault: boolean
       *   // 排序值
       *   sort: number
       *   // 备注
       *   remark?: object
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       * }>
       * ```
       */
      MallAddressesController_findCurrentUserAddresses<Config extends Alova2MethodConfig<CustomerAddressVo[]>>(
        config?: Config
      ): Alova2Method<CustomerAddressVo[], 'general.MallAddressesController_findCurrentUserAddresses', Config>;
      /**
       * ---
       *
       * [POST] 新增当前登录用户收货地址
       *
       * **path:** /mall/addresses
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 收货人
       *   receiverName: string
       *   // 收货电话
       *   receiverPhone: string
       *   // 省
       *   province?: string
       *   // 市
       *   city?: string
       *   // 区/县
       *   district?: string
       *   // 详细地址
       *   address: string
       *   // 邮编
       *   postalCode?: string
       *   // 地址标签，如家/公司
       *   tag?: string
       *   // 是否默认地址
       *   isDefault?: boolean
       *   // 排序值
       *   sort?: number
       *   // 备注
       *   remark?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 地址ID
       *   id: number
       *   // 客户ID
       *   customerId: number
       *   // 收货人
       *   receiverName: string
       *   // 收货电话
       *   receiverPhone: string
       *   // 省
       *   province?: object
       *   // 市
       *   city?: object
       *   // 区/县
       *   district?: object
       *   // 详细地址
       *   address: string
       *   // 完整地址
       *   fullAddress: string
       *   // 邮编
       *   postalCode?: object
       *   // 标签
       *   tag?: object
       *   // 是否默认地址
       *   isDefault: boolean
       *   // 排序值
       *   sort: number
       *   // 备注
       *   remark?: object
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       * }
       * ```
       */
      MallAddressesController_createCurrentUserAddress<
        Config extends Alova2MethodConfig<CustomerAddressVo> & {
          data: CreateCustomerAddressDto;
        }
      >(
        config: Config
      ): Alova2Method<CustomerAddressVo, 'general.MallAddressesController_createCurrentUserAddress', Config>;
      /**
       * ---
       *
       * [GET] 获取当前登录用户默认收货地址
       *
       * **path:** /mall/addresses/default
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 地址ID
       *   id: number
       *   // 客户ID
       *   customerId: number
       *   // 收货人
       *   receiverName: string
       *   // 收货电话
       *   receiverPhone: string
       *   // 省
       *   province?: object
       *   // 市
       *   city?: object
       *   // 区/县
       *   district?: object
       *   // 详细地址
       *   address: string
       *   // 完整地址
       *   fullAddress: string
       *   // 邮编
       *   postalCode?: object
       *   // 标签
       *   tag?: object
       *   // 是否默认地址
       *   isDefault: boolean
       *   // 排序值
       *   sort: number
       *   // 备注
       *   remark?: object
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       * }
       * ```
       */
      MallAddressesController_findDefaultAddress<Config extends Alova2MethodConfig<CustomerAddressVo>>(
        config?: Config
      ): Alova2Method<CustomerAddressVo, 'general.MallAddressesController_findDefaultAddress', Config>;
      /**
       * ---
       *
       * [GET] 获取当前登录用户收货地址详情
       *
       * **path:** /mall/addresses/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 地址ID
       *   id: number
       *   // 客户ID
       *   customerId: number
       *   // 收货人
       *   receiverName: string
       *   // 收货电话
       *   receiverPhone: string
       *   // 省
       *   province?: object
       *   // 市
       *   city?: object
       *   // 区/县
       *   district?: object
       *   // 详细地址
       *   address: string
       *   // 完整地址
       *   fullAddress: string
       *   // 邮编
       *   postalCode?: object
       *   // 标签
       *   tag?: object
       *   // 是否默认地址
       *   isDefault: boolean
       *   // 排序值
       *   sort: number
       *   // 备注
       *   remark?: object
       *   // 创建时间
       *   createdAt: string
       *   // 更新时间
       *   updatedAt: string
       * }
       * ```
       */
      MallAddressesController_findCurrentUserAddress<
        Config extends Alova2MethodConfig<CustomerAddressVo> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<CustomerAddressVo, 'general.MallAddressesController_findCurrentUserAddress', Config>;
      /**
       * ---
       *
       * [DELETE] 删除当前登录用户收货地址
       *
       * **path:** /mall/addresses/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallAddressesController_removeCurrentUserAddress<
        Config extends Alova2MethodConfig<null> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallAddressesController_removeCurrentUserAddress', Config>;
      /**
       * ---
       *
       * [GET] 获取我的订单列表
       *
       * **path:** /mall/orders
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 订单列表
       *   // [items] start
       *   // [items] end
       *   data: Array<{
       *     // 订单ID
       *     id: number
       *     // 订单号
       *     orderNo: string
       *     // 订单状态
       *     status: string
       *     // 支付状态
       *     payStatus: string
       *     // 发货状态
       *     shipStatus: string
       *     // 下单时间
       *     orderDate: string
       *     // 支付截止时间
       *     expireAt: object | null
       *     // 商品总额
       *     totalAmount: number
       *     // 应付金额
       *     payable: number
       *     // 已付金额
       *     paid: number
       *     // 商品件数
       *     itemCount: number
       *     // 订单商品
       *     // [items] start
       *     // [items] end
       *     items: Array<{
       *       // 商品ID
       *       productId: number
       *       // SKU ID
       *       skuId: number
       *       // 商品名称
       *       productName: string
       *       // SKU 编码
       *       skuCode: string
       *       // 规格
       *       specs: object
       *       // 商品图片
       *       image: object | null
       *       // 单价
       *       price: number
       *       // 数量
       *       quantity: number
       *       // 金额
       *       amount: number
       *     }>
       *   }>
       *   // 分页信息
       *   meta: {
       *     // 当前页码
       *     page: number
       *     // 每页数量
       *     pageSize: number
       *     // 总记录数
       *     total: number
       *     // 总页数
       *     totalPages: number
       *   }
       * }
       * ```
       */
      MallOrdersController_findOrders<Config extends Alova2MethodConfig<MallOrderListResponseVo>>(
        config?: Config
      ): Alova2Method<MallOrderListResponseVo, 'general.MallOrdersController_findOrders', Config>;
      /**
       * ---
       *
       * [POST] 创建商城订单
       *
       * **path:** /mall/orders
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 订单ID
       *   id: number
       *   // 订单号
       *   orderNo: string
       *   // 订单来源
       *   source: 'cart' | 'product-detail'
       *   // 商品总金额
       *   totalAmount: number
       *   // 应付金额
       *   payable: number
       *   // 优惠金额
       *   discount: number
       *   // 优惠券领取记录 ID
       *   couponReceiveId: object | null
       *   // 优惠券名称
       *   couponName: object | null
       *   // 商品件数
       *   itemCount: number
       *   // 订单状态
       *   status: string
       *   // 支付状态
       *   payStatus: string
       *   // 支付截止时间
       *   expireAt?: object | null
       * }
       * ```
       */
      MallOrdersController_createOrder<
        Config extends Alova2MethodConfig<MallCreateOrderVo> & {
          data: CreateMallOrderDto;
        }
      >(
        config: Config
      ): Alova2Method<MallCreateOrderVo, 'general.MallOrdersController_createOrder', Config>;
      /**
       * ---
       *
       * [GET] 获取我的订单详情
       *
       * **path:** /mall/orders/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 订单ID
       *   id: number
       *   // 订单号
       *   orderNo: string
       *   // 订单状态
       *   status: string
       *   // 支付状态
       *   payStatus: string
       *   // 发货状态
       *   shipStatus: string
       *   // 下单时间
       *   orderDate: string
       *   // 支付截止时间
       *   expireAt: object | null
       *   // 商品总额
       *   totalAmount: number
       *   // 应付金额
       *   payable: number
       *   // 已付金额
       *   paid: number
       *   // 商品件数
       *   itemCount: number
       *   // 订单商品
       *   // [items] start
       *   // [items] end
       *   items: Array<{
       *     // 商品ID
       *     productId: number
       *     // SKU ID
       *     skuId: number
       *     // 商品名称
       *     productName: string
       *     // SKU 编码
       *     skuCode: string
       *     // 规格
       *     specs: object
       *     // 商品图片
       *     image: object | null
       *     // 单价
       *     price: number
       *     // 数量
       *     quantity: number
       *     // 金额
       *     amount: number
       *   }>
       *   // 收货人
       *   receiverName: object | null
       *   // 收货电话
       *   receiverPhone: object | null
       *   // 收货地址
       *   receiverAddress: object | null
       *   // 优惠金额
       *   discount: number
       *   // 运费
       *   freight: number
       *   // 支付时间
       *   payDate: object | null
       *   // 取消时间
       *   cancelDate: object | null
       *   // 发货时间
       *   shipDate: object | null
       *   // 收货时间
       *   receiveDate: object | null
       *   // 支付方式
       *   paymentMethod: object | null
       *   // 优惠券领取记录 ID
       *   couponReceiveId: object | null
       *   // 优惠券名称
       *   couponName: object | null
       * }
       * ```
       */
      MallOrdersController_findOrderDetail<
        Config extends Alova2MethodConfig<MallOrderDetailVo> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallOrderDetailVo, 'general.MallOrdersController_findOrderDetail', Config>;
      /**
       * ---
       *
       * [DELETE] 删除商城订单
       *
       * **path:** /mall/orders/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallOrdersController_removeOrder<
        Config extends Alova2MethodConfig<null> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallOrdersController_removeOrder', Config>;
      /**
       * ---
       *
       * [POST] 支付商城订单
       *
       * **path:** /mall/orders/{id}/pay
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 支付单ID
       *   paymentId: object | null
       *   // 订单ID
       *   id: number
       *   // 订单号
       *   orderNo: string
       *   // 支付状态
       *   payStatus: string
       *   // 订单状态
       *   status: string
       *   // 已付金额
       *   paid: number
       *   // 支付单状态
       *   paymentStatus: string
       *   // 支付方式
       *   method: object | null
       *   // 商户支付单号
       *   outTradeNo: object | null
       *   // 支付完成时间
       *   payDate: object | null
       *   // 微信小程序支付参数
       *   paymentConfig?: object | null
       * }
       * ```
       */
      MallOrdersController_payOrder<
        Config extends Alova2MethodConfig<MallPayOrderVo> & {
          pathParams: {
            id: number;
          };
          data: PayMallOrderDto;
        }
      >(
        config: Config
      ): Alova2Method<MallPayOrderVo, 'general.MallOrdersController_payOrder', Config>;
      /**
       * ---
       *
       * [GET] 查询商城订单支付状态
       *
       * **path:** /mall/orders/{id}/payment-status
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 支付单ID
       *   paymentId: object | null
       *   // 订单ID
       *   id: number
       *   // 订单号
       *   orderNo: string
       *   // 支付状态
       *   payStatus: string
       *   // 订单状态
       *   status: string
       *   // 已付金额
       *   paid: number
       *   // 支付单状态
       *   paymentStatus: string
       *   // 支付方式
       *   method: object | null
       *   // 商户支付单号
       *   outTradeNo: object | null
       *   // 支付完成时间
       *   payDate: object | null
       *   // 微信小程序支付参数
       *   paymentConfig?: object | null
       * }
       * ```
       */
      MallOrdersController_getPaymentStatus<
        Config extends Alova2MethodConfig<MallPayOrderVo> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallPayOrderVo, 'general.MallOrdersController_getPaymentStatus', Config>;
      /**
       * ---
       *
       * [POST] 微信支付回调通知
       *
       * **path:** /mall/payments/wechat/notify
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallPaymentsController_wechatNotify<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'general.MallPaymentsController_wechatNotify', Config>;
      /**
       * ---
       *
       * [GET] 获取商品评价列表
       *
       * **path:** /mall/products/{id}/reviews
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 评分筛选
       *   rating?: number
       *   // 是否只看有图评价
       *   hasImage?: boolean
       *   // 页码
       *   page?: number
       *   // 每页数量
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallReviewsController_findProductReviews<
        Config extends Alova2MethodConfig<null> & {
          pathParams: {
            id: number;
          };
          params: {
            /**
             * 评分筛选
             */
            rating?: number;
            /**
             * 是否只看有图评价
             */
            hasImage?: boolean;
            /**
             * 页码
             */
            page?: number;
            /**
             * 每页数量
             */
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallReviewsController_findProductReviews', Config>;
      /**
       * ---
       *
       * [GET] 获取商品评价统计
       *
       * **path:** /mall/products/{id}/review-stats
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallReviewsController_getProductReviewStats<
        Config extends Alova2MethodConfig<null> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallReviewsController_getProductReviewStats', Config>;
      /**
       * ---
       *
       * [POST] 提交评价
       *
       * **path:** /mall/reviews
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 订单明细ID
       *   orderItemId: number
       *   // 评分，1-5
       *   rating: number
       *   // 评价内容
       *   content?: string
       *   // 评价图片列表
       *   // [items] start
       *   // [items] end
       *   images?: string[]
       *   // 是否匿名
       *   isAnonymous?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallReviewsController_createReview<
        Config extends Alova2MethodConfig<null> & {
          data: CreateMallReviewDto;
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallReviewsController_createReview', Config>;
      /**
       * ---
       *
       * [GET] 获取我的评价
       *
       * **path:** /mall/reviews/my
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   page: number
       *   pageSize: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallReviewsController_findMyReviews<
        Config extends Alova2MethodConfig<null> & {
          params: {
            page: number;
            pageSize: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallReviewsController_findMyReviews', Config>;
      /**
       * ---
       *
       * [GET] 获取待评价订单商品
       *
       * **path:** /mall/reviews/pending
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallReviewsController_findPendingReviews<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'general.MallReviewsController_findPendingReviews', Config>;
      /**
       * ---
       *
       * [GET] 获取我的余额概览
       *
       * **path:** /mall/balance
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 账户ID
       *   id: number
       *   // 客户ID
       *   customerId: number
       *   // 可用余额
       *   availableBalance: string
       *   // 冻结余额
       *   frozenBalance: string
       *   // 累计充值
       *   totalRecharged: string
       *   // 累计消费
       *   totalConsumed: string
       *   // 累计退款
       *   totalRefunded: string
       *   // 最近更新时间
       *   updatedAt: string
       * }
       * ```
       */
      MallBalanceController_getSummary<Config extends Alova2MethodConfig<MallBalanceSummaryVo>>(
        config?: Config
      ): Alova2Method<MallBalanceSummaryVo, 'general.MallBalanceController_getSummary', Config>;
      /**
       * ---
       *
       * [GET] 获取我的余额流水
       *
       * **path:** /mall/balance/logs
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 流水类型
       *   type?: 'RECHARGE' | 'CONSUME' | 'REFUND' | 'ADJUST_INCREASE' | 'ADJUST_DECREASE'
       *   // 页码
       *   page?: number
       *   // 每页条数
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [items] start
       *   // [items] end
       *   data: Array<{
       *     // 流水ID
       *     id: number
       *     // 流水类型
       *     type: 'RECHARGE' | 'CONSUME' | 'REFUND' | 'ADJUST_INCREASE' | 'ADJUST_DECREASE'
       *     // 流水类型文案
       *     typeText: string
       *     // 变动金额
       *     changeAmount: string
       *     // 变动前余额
       *     balanceBefore: string
       *     // 变动后余额
       *     balanceAfter: string
       *     // 业务单号
       *     bizNo?: object | null
       *     // 备注
       *     remark?: object | null
       *     // 创建时间
       *     createdAt: string
       *   }>
       *   // 分页信息
       *   meta: object
       * }
       * ```
       */
      MallBalanceController_getLogs<
        Config extends Alova2MethodConfig<MallBalanceLogListVo> & {
          params: {
            /**
             * 流水类型
             */
            type?: 'RECHARGE' | 'CONSUME' | 'REFUND' | 'ADJUST_INCREASE' | 'ADJUST_DECREASE';
            /**
             * 页码
             */
            page?: number;
            /**
             * 每页条数
             */
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallBalanceLogListVo, 'general.MallBalanceController_getLogs', Config>;
      /**
       * ---
       *
       * [POST] 创建余额充值
       *
       * **path:** /mall/balance/recharge
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 充值金额
       *   amount: number
       *   // 充值方式
       *   method: 'WECHAT'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 充值单ID
       *   id: number
       *   // 账户ID
       *   accountId: number
       *   // 充值金额
       *   amount: string
       *   // 充值方式
       *   method: 'CASH' | 'BANK' | 'ALIPAY' | 'WECHAT' | 'CREDIT' | 'BALANCE'
       *   // 当前可用余额
       *   availableBalance: string
       *   // 充值单号
       *   rechargeNo: string
       *   // 充值状态
       *   status: string
       *   // 商户支付单号
       *   outTradeNo: object | null
       *   // 微信小程序支付参数
       *   paymentConfig?: object | null
       *   // 充值时间
       *   createdAt: string
       *   // 支付完成时间
       *   paidAt: object | null
       * }
       * ```
       */
      MallBalanceController_recharge<
        Config extends Alova2MethodConfig<MallBalanceRechargeVo> & {
          data: CreateMallBalanceRechargeDto;
        }
      >(
        config: Config
      ): Alova2Method<MallBalanceRechargeVo, 'general.MallBalanceController_recharge', Config>;
      /**
       * ---
       *
       * [GET] 查询余额充值状态
       *
       * **path:** /mall/balance/recharges/{id}/status
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 充值单ID
       *   id: number
       *   // 账户ID
       *   accountId: number
       *   // 充值金额
       *   amount: string
       *   // 充值方式
       *   method: 'CASH' | 'BANK' | 'ALIPAY' | 'WECHAT' | 'CREDIT' | 'BALANCE'
       *   // 当前可用余额
       *   availableBalance: string
       *   // 充值单号
       *   rechargeNo: string
       *   // 充值状态
       *   status: string
       *   // 商户支付单号
       *   outTradeNo: object | null
       *   // 微信小程序支付参数
       *   paymentConfig?: object | null
       *   // 充值时间
       *   createdAt: string
       *   // 支付完成时间
       *   paidAt: object | null
       * }
       * ```
       */
      MallBalanceController_getRechargeStatus<
        Config extends Alova2MethodConfig<MallBalanceRechargeVo> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallBalanceRechargeVo, 'general.MallBalanceController_getRechargeStatus', Config>;
      /**
       * ---
       *
       * [GET] 获取我的收藏列表
       *
       * **path:** /mall/favorites
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 关键词，支持商品名称
       *   keyword?: string
       *   // 页码
       *   page?: number
       *   // 每页条数
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [items] start
       *   // [items] end
       *   data: Array<{
       *     // 商品ID
       *     id: number
       *     // 商品名称
       *     name: string
       *     // SPU编码
       *     spuCode: string
       *     // 分类ID
       *     categoryId: number
       *     // 品牌ID
       *     brandId: object | null
       *     // 单位ID
       *     unitId: number
       *     // 商品描述
       *     description: object | null
       *     // 商品详情（富文本HTML）
       *     detail: object | null
       *     // 商品主图
       *     mainImage: object | null
       *     // 商品图片列表
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     images: string[] | null
       *     // 规格模板
       *     specTemplate: Record<string, any> | null
       *     // 是否启用
       *     isEnabled: boolean
       *     // 是否在商城上架
       *     mallEnabled: boolean
       *     // 总可用库存
       *     totalAvailable?: number
       *     // 是否有库存
       *     hasStock?: boolean
       *     // 商城扩展信息
       *     mallInfo: Record<string, any> | null
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *     // 分类信息
       *     category: {
       *       // 分类ID
       *       id: number
       *       // 分类名称
       *       name: string
       *       // 分类编码
       *       code: string
       *       // 子标题
       *       subtitle: object | null
       *       // 备注
       *       remark: object | null
       *       // 父级ID
       *       parentId: object | null
       *       // 层级
       *       level: number
       *       // 排序号
       *       sort: number
       *       // 是否作为商城搜索推荐分类
       *       mallRecommend: boolean
       *       // 商城搜索推荐排序号
       *       mallRecommendSort: number
       *       // 分类图标
       *       icon: object | null
       *       // 分类图标 URL
       *       iconUrl: object | null
       *       // 分类图片
       *       image: object | null
       *       // 是否启用
       *       isEnabled: boolean
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // 品牌信息
       *     brand: {
       *       // 品牌ID
       *       id: number
       *       // 品牌名称
       *       name: string
       *       // 品牌logo
       *       logo: object | null
       *       // 品牌描述
       *       description: object | null
       *       // 排序
       *       sort: number
       *       // 是否启用
       *       isEnabled: boolean
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // 单位信息
       *     unit: {
       *       // 单位ID
       *       id: number
       *       // 单位名称
       *       name: string
       *       // 单位编码
       *       code: string
       *       // 排序
       *       sort: number
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // SKU列表
       *     // [items] start
       *     // [items] end
       *     skus?: Array<Record<string, any>>
       *     // 当前用户是否已收藏
       *     isFavorite?: boolean
       *     // 热门标签
       *     hotLabel?: object | null
       *     // 最低价
       *     minPrice: number
       *     // 最高价
       *     maxPrice: number
       *     // 价格区间展示文本
       *     priceRange: string
       *     // 收藏ID
       *     favoriteId: number
       *     // 收藏时间
       *     favoriteAt: string
       *   }>
       *   meta: {
       *     // 当前页码
       *     page: number
       *     // 每页数量
       *     pageSize: number
       *     // 总记录数
       *     total: number
       *     // 总页数
       *     totalPages: number
       *   }
       * }
       * ```
       */
      MallFavoritesController_findFavorites<
        Config extends Alova2MethodConfig<FavoriteListVo> & {
          params: {
            /**
             * 关键词，支持商品名称
             */
            keyword?: string;
            /**
             * 页码
             */
            page?: number;
            /**
             * 每页条数
             */
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<FavoriteListVo, 'general.MallFavoritesController_findFavorites', Config>;
      /**
       * ---
       *
       * [POST] 添加商品收藏
       *
       * **path:** /mall/favorites
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 商品ID
       *   productId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallFavoritesController_createFavorite<
        Config extends Alova2MethodConfig<null> & {
          data: CreateFavoriteDto;
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallFavoritesController_createFavorite', Config>;
      /**
       * ---
       *
       * [GET] 批量检查商品收藏状态
       *
       * **path:** /mall/favorites/check
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 商品ID列表，支持逗号分隔字符串或数组
       *   // [items] start
       *   // [items] end
       *   productIds?: number[]
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 商品ID
       *   productId: number
       *   // 是否已收藏
       *   isFavorite: boolean
       * }>
       * ```
       */
      MallFavoritesController_checkFavoriteStatus<
        Config extends Alova2MethodConfig<FavoriteStatusVo[]> & {
          params: {
            /**
             * 商品ID列表，支持逗号分隔字符串或数组
             */
            productIds?: number[];
          };
        }
      >(
        config: Config
      ): Alova2Method<FavoriteStatusVo[], 'general.MallFavoritesController_checkFavoriteStatus', Config>;
      /**
       * ---
       *
       * [DELETE] 取消商品收藏
       *
       * **path:** /mall/favorites/{productId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   productId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallFavoritesController_removeFavorite<
        Config extends Alova2MethodConfig<null> & {
          pathParams: {
            productId: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallFavoritesController_removeFavorite', Config>;
      /**
       * ---
       *
       * [GET] 获取我的浏览历史
       *
       * **path:** /mall/histories
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 关键词，支持商品名称
       *   keyword?: string
       *   // 页码
       *   page?: number
       *   // 每页条数
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [items] start
       *   // [items] end
       *   data: Array<{
       *     // 商品ID
       *     id: number
       *     // 商品名称
       *     name: string
       *     // SPU编码
       *     spuCode: string
       *     // 分类ID
       *     categoryId: number
       *     // 品牌ID
       *     brandId: object | null
       *     // 单位ID
       *     unitId: number
       *     // 商品描述
       *     description: object | null
       *     // 商品详情（富文本HTML）
       *     detail: object | null
       *     // 商品主图
       *     mainImage: object | null
       *     // 商品图片列表
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     images: string[] | null
       *     // 规格模板
       *     specTemplate: Record<string, any> | null
       *     // 是否启用
       *     isEnabled: boolean
       *     // 是否在商城上架
       *     mallEnabled: boolean
       *     // 总可用库存
       *     totalAvailable?: number
       *     // 是否有库存
       *     hasStock?: boolean
       *     // 商城扩展信息
       *     mallInfo: Record<string, any> | null
       *     // 创建时间
       *     createdAt: string
       *     // 更新时间
       *     updatedAt: string
       *     // 分类信息
       *     category: {
       *       // 分类ID
       *       id: number
       *       // 分类名称
       *       name: string
       *       // 分类编码
       *       code: string
       *       // 子标题
       *       subtitle: object | null
       *       // 备注
       *       remark: object | null
       *       // 父级ID
       *       parentId: object | null
       *       // 层级
       *       level: number
       *       // 排序号
       *       sort: number
       *       // 是否作为商城搜索推荐分类
       *       mallRecommend: boolean
       *       // 商城搜索推荐排序号
       *       mallRecommendSort: number
       *       // 分类图标
       *       icon: object | null
       *       // 分类图标 URL
       *       iconUrl: object | null
       *       // 分类图片
       *       image: object | null
       *       // 是否启用
       *       isEnabled: boolean
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // 品牌信息
       *     brand: {
       *       // 品牌ID
       *       id: number
       *       // 品牌名称
       *       name: string
       *       // 品牌logo
       *       logo: object | null
       *       // 品牌描述
       *       description: object | null
       *       // 排序
       *       sort: number
       *       // 是否启用
       *       isEnabled: boolean
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // 单位信息
       *     unit: {
       *       // 单位ID
       *       id: number
       *       // 单位名称
       *       name: string
       *       // 单位编码
       *       code: string
       *       // 排序
       *       sort: number
       *       // 创建时间
       *       createdAt: string
       *       // 更新时间
       *       updatedAt: string
       *     }
       *     // SKU列表
       *     // [items] start
       *     // [items] end
       *     skus?: Array<Record<string, any>>
       *     // 当前用户是否已收藏
       *     isFavorite?: boolean
       *     // 热门标签
       *     hotLabel?: object | null
       *     // 最低价
       *     minPrice: number
       *     // 最高价
       *     maxPrice: number
       *     // 价格区间展示文本
       *     priceRange: string
       *     // 浏览记录ID
       *     historyId: number
       *     // 浏览次数
       *     viewCount: number
       *     // 首次浏览时间
       *     firstViewedAt: string
       *     // 最近浏览时间
       *     lastViewedAt: string
       *   }>
       *   meta: {
       *     // 当前页码
       *     page: number
       *     // 每页数量
       *     pageSize: number
       *     // 总记录数
       *     total: number
       *     // 总页数
       *     totalPages: number
       *   }
       * }
       * ```
       */
      MallBrowseHistoriesController_findHistories<
        Config extends Alova2MethodConfig<BrowseHistoryListVo> & {
          params: {
            /**
             * 关键词，支持商品名称
             */
            keyword?: string;
            /**
             * 页码
             */
            page?: number;
            /**
             * 每页条数
             */
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<BrowseHistoryListVo, 'general.MallBrowseHistoriesController_findHistories', Config>;
      /**
       * ---
       *
       * [POST] 记录商品浏览历史
       *
       * **path:** /mall/histories
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 商品ID
       *   productId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallBrowseHistoriesController_createHistory<
        Config extends Alova2MethodConfig<null> & {
          data: CreateBrowseHistoryDto;
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallBrowseHistoriesController_createHistory', Config>;
      /**
       * ---
       *
       * [DELETE] 清空浏览历史
       *
       * **path:** /mall/histories/clear
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallBrowseHistoriesController_clearHistories<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'general.MallBrowseHistoriesController_clearHistories', Config>;
      /**
       * ---
       *
       * [DELETE] 删除单条浏览历史
       *
       * **path:** /mall/histories/{productId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   productId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      MallBrowseHistoriesController_removeHistory<
        Config extends Alova2MethodConfig<null> & {
          pathParams: {
            productId: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<null, 'general.MallBrowseHistoriesController_removeHistory', Config>;
      /**
       * ---
       *
       * [GET] 获取我的优惠券概览
       *
       * **path:** /mall/coupons/summary
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 未使用优惠券数量
       *   unusedCount: number
       *   // 已使用优惠券数量
       *   usedCount: number
       *   // 已过期优惠券数量
       *   expiredCount: number
       *   // 可领取优惠券数量
       *   claimableCount: number
       * }
       * ```
       */
      MallCouponsController_getSummary<Config extends Alova2MethodConfig<MallCouponSummaryVo>>(
        config?: Config
      ): Alova2Method<MallCouponSummaryVo, 'general.MallCouponsController_getSummary', Config>;
      /**
       * ---
       *
       * [GET] 获取我的优惠券列表
       *
       * **path:** /mall/coupons
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 状态筛选
       *   status?: 'UNUSED' | 'USED' | 'EXPIRED'
       *   // 页码
       *   page?: number
       *   // 每页条数
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [items] start
       *   // [items] end
       *   data: Array<{
       *     // 领取记录 ID
       *     id: number
       *     // 优惠券 ID
       *     couponId: number
       *     // 优惠券名称
       *     name: string
       *     // 优惠券编码
       *     code: string
       *     // 优惠券金额
       *     discountAmount: number
       *     // 使用门槛金额
       *     thresholdAmount: number
       *     // 优惠文案
       *     discountLabel: string
       *     // 使用门槛文案
       *     thresholdLabel: string
       *     // 状态
       *     status: 'UNUSED' | 'USED' | 'EXPIRED' | 'INVALID'
       *     // 状态文案
       *     statusText: string
       *     // 来源文案
       *     sourceText: string
       *     // 有效期开始时间
       *     validFrom: string
       *     // 有效期结束时间
       *     validTo: string
       *     // 有效期文案
       *     validPeriodText: string
       *     // 使用说明
       *     description: object | null
       *     // 是否临近到期
       *     isExpiringSoon: boolean
       *   }>
       *   meta: {
       *     // 当前页码
       *     page: number
       *     // 每页数量
       *     pageSize: number
       *     // 总记录数
       *     total: number
       *     // 总页数
       *     totalPages: number
       *   }
       * }
       * ```
       */
      MallCouponsController_findWallet<
        Config extends Alova2MethodConfig<MallCouponWalletListVo> & {
          params: {
            /**
             * 状态筛选
             */
            status?: 'UNUSED' | 'USED' | 'EXPIRED';
            /**
             * 页码
             */
            page?: number;
            /**
             * 每页条数
             */
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallCouponWalletListVo, 'general.MallCouponsController_findWallet', Config>;
      /**
       * ---
       *
       * [GET] 获取领券中心列表
       *
       * **path:** /mall/coupons/center
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 状态筛选
       *   status?: 'UNUSED' | 'USED' | 'EXPIRED'
       *   // 页码
       *   page?: number
       *   // 每页条数
       *   pageSize?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [items] start
       *   // [items] end
       *   data: Array<{
       *     // 优惠券 ID
       *     id: number
       *     // 优惠券名称
       *     name: string
       *     // 优惠券编码
       *     code: string
       *     // 优惠券金额
       *     discountAmount: number
       *     // 使用门槛金额
       *     thresholdAmount: number
       *     // 优惠文案
       *     discountLabel: string
       *     // 使用门槛文案
       *     thresholdLabel: string
       *     // 剩余数量
       *     remainingCount: object | null
       *     // 个人已领取次数
       *     claimedCount: number
       *     // 是否可领取
       *     canClaim: boolean
       *     // 按钮文案
       *     actionText: string
       *     // 标签文案
       *     tagText: object | null
       *     // 有效期开始时间
       *     startTime: string
       *     // 有效期结束时间
       *     endTime: string
       *     // 有效期文案
       *     validPeriodText: string
       *     // 使用说明
       *     description: object | null
       *   }>
       *   meta: {
       *     // 当前页码
       *     page: number
       *     // 每页数量
       *     pageSize: number
       *     // 总记录数
       *     total: number
       *     // 总页数
       *     totalPages: number
       *   }
       * }
       * ```
       */
      MallCouponsController_findCenter<
        Config extends Alova2MethodConfig<MallCouponCenterListVo> & {
          params: {
            /**
             * 状态筛选
             */
            status?: 'UNUSED' | 'USED' | 'EXPIRED';
            /**
             * 页码
             */
            page?: number;
            /**
             * 每页条数
             */
            pageSize?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallCouponCenterListVo, 'general.MallCouponsController_findCenter', Config>;
      /**
       * ---
       *
       * [POST] 领取优惠券
       *
       * **path:** /mall/coupons/{id}/claim
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 是否成功
       *   success: boolean
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      MallCouponsController_claimCoupon<
        Config extends Alova2MethodConfig<MallCouponClaimResultVo> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<MallCouponClaimResultVo, 'general.MallCouponsController_claimCoupon', Config>;
    };
  }

  var Apis: Apis;
}
